/* Bizzing Bee — kid-friendly quotations from famous people.
   Each: {q: quote, a: author, c: category, who: short who-they-were}.
   Categories: courage kindness perseverance learning dreams friendship honesty
   curiosity teamwork imagination gratitude leadership happiness hardwork believe
   creativity nature change wisdom humor science sports reading.
   This seed set is expanded by the generation pipeline (see quotes-*.js merges). */
window.SB_QUOTES = (window.SB_QUOTES || []).concat([
  {q:"The only way to do great work is to love what you do.",a:"Steve Jobs",c:"hardwork",who:"co-founder of Apple"},
  {q:"You are never too old to set another goal or to dream a new dream.",a:"C.S. Lewis",c:"dreams",who:"author of Narnia"},
  {q:"It always seems impossible until it's done.",a:"Nelson Mandela",c:"perseverance",who:"South African leader"},
  {q:"Believe you can and you're halfway there.",a:"Theodore Roosevelt",c:"believe",who:"US president"},
  {q:"No act of kindness, no matter how small, is ever wasted.",a:"Aesop",c:"kindness",who:"ancient storyteller"},
  {q:"The future belongs to those who believe in the beauty of their dreams.",a:"Eleanor Roosevelt",c:"dreams",who:"US First Lady"},
  {q:"Try to be a rainbow in someone's cloud.",a:"Maya Angelou",c:"kindness",who:"poet and author"},
  {q:"A person who never made a mistake never tried anything new.",a:"Albert Einstein",c:"learning",who:"physicist"},
  {q:"Curiosity is the wick in the candle of learning.",a:"William Arthur Ward",c:"curiosity",who:"writer"},
  {q:"Imagination is more important than knowledge.",a:"Albert Einstein",c:"imagination",who:"physicist"},
  {q:"It does not matter how slowly you go as long as you do not stop.",a:"Confucius",c:"perseverance",who:"Chinese philosopher"},
  {q:"Whether you think you can, or you think you can't — you're right.",a:"Henry Ford",c:"believe",who:"carmaker"},
  {q:"Do what you can, with what you have, where you are.",a:"Theodore Roosevelt",c:"hardwork",who:"US president"},
  {q:"Alone we can do so little; together we can do so much.",a:"Helen Keller",c:"teamwork",who:"author and activist"},
  {q:"Kindness is a language which the deaf can hear and the blind can see.",a:"Mark Twain",c:"kindness",who:"American author"},
  {q:"The best way to predict the future is to create it.",a:"Abraham Lincoln",c:"leadership",who:"US president"},
  {q:"Courage is not the absence of fear, but the triumph over it.",a:"Nelson Mandela",c:"courage",who:"South African leader"},
  {q:"If you can dream it, you can do it.",a:"Walt Disney",c:"dreams",who:"animator and film-maker"},
  {q:"Wisdom begins in wonder.",a:"Socrates",c:"wisdom",who:"Greek philosopher"},
  {q:"The important thing is not to stop questioning.",a:"Albert Einstein",c:"curiosity",who:"physicist"},
  {q:"Little by little, one travels far.",a:"J.R.R. Tolkien",c:"perseverance",who:"author of The Hobbit"},
  {q:"You miss 100 percent of the shots you don't take.",a:"Wayne Gretzky",c:"courage",who:"ice-hockey legend"},
  {q:"We may encounter many defeats but we must not be defeated.",a:"Maya Angelou",c:"perseverance",who:"poet and author"},
  {q:"Change your thoughts and you change your world.",a:"Norman Vincent Peale",c:"change",who:"author"},
  {q:"The more that you read, the more things you will know.",a:"Dr. Seuss",c:"reading",who:"children's author"},
  {q:"Once you learn to read, you will be forever free.",a:"Frederick Douglass",c:"reading",who:"abolitionist and writer"},
  {q:"Honesty is the first chapter in the book of wisdom.",a:"Thomas Jefferson",c:"honesty",who:"US president"},
  {q:"In a gentle way, you can shake the world.",a:"Mahatma Gandhi",c:"change",who:"Indian leader"},
  {q:"Be the change that you wish to see in the world.",a:"Mahatma Gandhi",c:"change",who:"Indian leader"},
  {q:"Happiness is not something ready made. It comes from your own actions.",a:"Dalai Lama",c:"happiness",who:"Tibetan spiritual leader"},
  {q:"The best and most beautiful things in the world cannot be seen or even touched — they must be felt with the heart.",a:"Helen Keller",c:"happiness",who:"author and activist"},
  {q:"Genius is one percent inspiration and ninety-nine percent perspiration.",a:"Thomas Edison",c:"hardwork",who:"inventor"},
  {q:"I have not failed. I've just found 10,000 ways that won't work.",a:"Thomas Edison",c:"perseverance",who:"inventor"},
  {q:"Nothing is impossible; the word itself says 'I'm possible'!",a:"Audrey Hepburn",c:"believe",who:"actress"},
  {q:"Creativity is intelligence having fun.",a:"Albert Einstein",c:"creativity",who:"physicist"},
  {q:"Look deep into nature, and then you will understand everything better.",a:"Albert Einstein",c:"nature",who:"physicist"},
  {q:"To succeed in life, you need two things: ignorance and confidence.",a:"Mark Twain",c:"humor",who:"American author"},
  {q:"The man who does not read has no advantage over the man who cannot read.",a:"Mark Twain",c:"reading",who:"American author"},
  {q:"Somewhere, something incredible is waiting to be known.",a:"Carl Sagan",c:"science",who:"astronomer"},
  {q:"Science is a way of thinking much more than it is a body of knowledge.",a:"Carl Sagan",c:"science",who:"astronomer"},
  {q:"I am not afraid of storms, for I am learning how to sail my ship.",a:"Louisa May Alcott",c:"courage",who:"author of Little Women"},
  {q:"A friend is one who overlooks your broken fence and admires the flowers in your garden.",a:"Anonymous",c:"friendship",who:"a wise saying"},
  {q:"You can make new friends, but you cannot make old friends.",a:"Anonymous",c:"friendship",who:"a wise saying"},
  {q:"Gratitude turns what we have into enough.",a:"Anonymous",c:"gratitude",who:"a wise saying"},
  {q:"Start where you are. Use what you have. Do what you can.",a:"Arthur Ashe",c:"hardwork",who:"tennis champion"},
  {q:"Champions keep playing until they get it right.",a:"Billie Jean King",c:"sports",who:"tennis champion"},
  {q:"You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.",a:"Dr. Seuss",c:"believe",who:"children's author"},
  {q:"Today you are you! That is truer than true! There is no one alive who is you-er than you!",a:"Dr. Seuss",c:"believe",who:"children's author"},
  {q:"Why fit in when you were born to stand out?",a:"Dr. Seuss",c:"believe",who:"children's author"},
  {q:"A goal without a plan is just a wish.",a:"Antoine de Saint-Exupery",c:"leadership",who:"author of The Little Prince"},
  {q:"It is only with the heart that one can see rightly; what is essential is invisible to the eye.",a:"Antoine de Saint-Exupery",c:"kindness",who:"author of The Little Prince"},
  {q:"The way to get started is to quit talking and begin doing.",a:"Walt Disney",c:"hardwork",who:"animator and film-maker"},
  {q:"All our dreams can come true, if we have the courage to pursue them.",a:"Walt Disney",c:"dreams",who:"animator and film-maker"},
  {q:"You are braver than you believe, stronger than you seem, and smarter than you think.",a:"A.A. Milne",c:"courage",who:"author of Winnie-the-Pooh"},
  {q:"A little consideration, a little thought for others, makes all the difference.",a:"A.A. Milne",c:"kindness",who:"author of Winnie-the-Pooh"},
  {q:"The best way to find yourself is to lose yourself in the service of others.",a:"Mahatma Gandhi",c:"kindness",who:"Indian leader"},
  {q:"Live as if you were to die tomorrow. Learn as if you were to live forever.",a:"Mahatma Gandhi",c:"learning",who:"Indian leader"},
  {q:"Education is the most powerful weapon which you can use to change the world.",a:"Nelson Mandela",c:"learning",who:"South African leader"},
  {q:"It is our choices that show what we truly are, far more than our abilities.",a:"J.K. Rowling",c:"honesty",who:"author of Harry Potter"},
  {q:"Happiness can be found, even in the darkest of times, if one only remembers to turn on the light.",a:"J.K. Rowling",c:"happiness",who:"author of Harry Potter"},
  {q:"We are what we repeatedly do. Excellence, then, is not an act, but a habit.",a:"Aristotle",c:"hardwork",who:"Greek philosopher"},
  {q:"Knowing yourself is the beginning of all wisdom.",a:"Aristotle",c:"wisdom",who:"Greek philosopher"},
  {q:"Fall seven times, stand up eight.",a:"Japanese Proverb",c:"perseverance",who:"a traditional saying"},
  {q:"A journey of a thousand miles begins with a single step.",a:"Lao Tzu",c:"perseverance",who:"Chinese philosopher"},
  {q:"When you talk, you are only repeating what you already know. But if you listen, you may learn something new.",a:"Dalai Lama",c:"wisdom",who:"Tibetan spiritual leader"},
  {q:"Be kind whenever possible. It is always possible.",a:"Dalai Lama",c:"kindness",who:"Tibetan spiritual leader"},
  {q:"There is no substitute for hard work.",a:"Thomas Edison",c:"hardwork",who:"inventor"},
  {q:"Our greatest glory is not in never falling, but in rising every time we fall.",a:"Confucius",c:"perseverance",who:"Chinese philosopher"},
  {q:"Real knowledge is to know the extent of one's ignorance.",a:"Confucius",c:"learning",who:"Chinese philosopher"},
  {q:"Everything you can imagine is real.",a:"Pablo Picasso",c:"imagination",who:"painter"},
  {q:"Every child is an artist.",a:"Pablo Picasso",c:"creativity",who:"painter"},
  {q:"The earth has music for those who listen.",a:"William Shakespeare",c:"nature",who:"playwright"},
  {q:"We know what we are, but know not what we may be.",a:"William Shakespeare",c:"dreams",who:"playwright"},
  {q:"Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.",a:"Mark Twain",c:"courage",who:"American author"},
  {q:"Keep your face always toward the sunshine, and shadows will fall behind you.",a:"Walt Whitman",c:"happiness",who:"poet"},
  {q:"Not all those who wander are lost.",a:"J.R.R. Tolkien",c:"curiosity",who:"author of The Hobbit"},
  {q:"Even the smallest person can change the course of the future.",a:"J.R.R. Tolkien",c:"change",who:"author of The Hobbit"},
  {q:"Do not follow where the path may lead. Go instead where there is no path and leave a trail.",a:"Ralph Waldo Emerson",c:"courage",who:"essayist"},
  {q:"What lies behind us and what lies before us are tiny matters compared to what lies within us.",a:"Ralph Waldo Emerson",c:"believe",who:"essayist"},
  {q:"The only limit to our realization of tomorrow will be our doubts of today.",a:"Franklin D. Roosevelt",c:"believe",who:"US president"},
  {q:"Spread love everywhere you go. Let no one ever come to you without leaving happier.",a:"Mother Teresa",c:"kindness",who:"humanitarian"},
  {q:"If you can't feed a hundred people, then feed just one.",a:"Mother Teresa",c:"kindness",who:"humanitarian"},
  {q:"Turn your wounds into wisdom.",a:"Oprah Winfrey",c:"wisdom",who:"broadcaster"},
  {q:"The more you praise and celebrate your life, the more there is in life to celebrate.",a:"Oprah Winfrey",c:"gratitude",who:"broadcaster"},
  {q:"You must be the change you wish to see, and it starts with a single kind act.",a:"Anonymous",c:"change",who:"a wise saying"},
  {q:"Reading is to the mind what exercise is to the body.",a:"Joseph Addison",c:"reading",who:"writer"},
  {q:"There is more treasure in books than in all the pirate's loot on Treasure Island.",a:"Walt Disney",c:"reading",who:"animator and film-maker"},
  {q:"I can accept failure, everyone fails at something. But I can't accept not trying.",a:"Michael Jordan",c:"perseverance",who:"basketball legend"},
  {q:"I've missed more than 9,000 shots in my career. I've failed over and over — and that is why I succeed.",a:"Michael Jordan",c:"perseverance",who:"basketball legend"},
  {q:"It always seems impossible until it is done, so keep going.",a:"Anonymous",c:"perseverance",who:"a wise saying"},
  {q:"Great things are done by a series of small things brought together.",a:"Vincent van Gogh",c:"hardwork",who:"painter"},
  {q:"I dream my painting and I paint my dream.",a:"Vincent van Gogh",c:"imagination",who:"painter"},
  {q:"Float like a butterfly, sting like a bee.",a:"Muhammad Ali",c:"sports",who:"boxing champion"},
  {q:"Don't count the days, make the days count.",a:"Muhammad Ali",c:"hardwork",who:"boxing champion"},
  {q:"The mind is everything. What you think you become.",a:"Buddha",c:"wisdom",who:"spiritual teacher"},
  {q:"Thousands of candles can be lit from a single candle, and the life of the candle will not be shortened.",a:"Buddha",c:"kindness",who:"spiritual teacher"},
  {q:"An investment in knowledge pays the best interest.",a:"Benjamin Franklin",c:"learning",who:"scientist and statesman"},
  {q:"Tell me and I forget. Teach me and I remember. Involve me and I learn.",a:"Benjamin Franklin",c:"learning",who:"scientist and statesman"},
  {q:"Be curious, not judgmental.",a:"Walt Whitman",c:"curiosity",who:"poet"},
  {q:"The scientist is not a person who gives the right answers, he's one who asks the right questions.",a:"Claude Levi-Strauss",c:"curiosity",who:"anthropologist"},
  {q:"Nothing in life is to be feared, it is only to be understood.",a:"Marie Curie",c:"courage",who:"scientist, two-time Nobel winner"},
  {q:"Be less curious about people and more curious about ideas.",a:"Marie Curie",c:"curiosity",who:"scientist, two-time Nobel winner"},
  {q:"Somewhere, something incredible is waiting to be discovered by a curious mind.",a:"Anonymous",c:"science",who:"a wise saying"},
  {q:"Teamwork makes the dream work.",a:"John C. Maxwell",c:"teamwork",who:"leadership author"},
  {q:"A leader is one who knows the way, goes the way, and shows the way.",a:"John C. Maxwell",c:"leadership",who:"leadership author"},
  {q:"Family is not an important thing. It's everything.",a:"Michael J. Fox",c:"friendship",who:"actor"},
  {q:"Laughter is the sun that drives winter from the human face.",a:"Victor Hugo",c:"humor",who:"author of Les Miserables"},
  {q:"Even if you are on the right track, you'll get run over if you just sit there.",a:"Will Rogers",c:"hardwork",who:"humorist"},
  {q:"A day without laughter is a day wasted.",a:"Charlie Chaplin",c:"humor",who:"actor and film-maker"},
  {q:"You'll never find a rainbow if you're looking down.",a:"Charlie Chaplin",c:"happiness",who:"actor and film-maker"},
  {q:"The roots of education are bitter, but the fruit is sweet.",a:"Aristotle",c:"learning",who:"Greek philosopher"},
  {q:"Anyone who has never made a mistake has never tried anything new.",a:"Albert Einstein",c:"courage",who:"physicist"},
  {q:"Strive not to be a success, but rather to be of value.",a:"Albert Einstein",c:"kindness",who:"physicist"},
  {q:"The good life is one inspired by love and guided by knowledge.",a:"Bertrand Russell",c:"wisdom",who:"philosopher"},
  {q:"To handle yourself, use your head; to handle others, use your heart.",a:"Eleanor Roosevelt",c:"leadership",who:"US First Lady"},
  {q:"No one can make you feel inferior without your consent.",a:"Eleanor Roosevelt",c:"believe",who:"US First Lady"},
  {q:"Where there is love there is life.",a:"Mahatma Gandhi",c:"kindness",who:"Indian leader"},
  {q:"Arise, awake, and stop not until the goal is reached.",a:"Swami Vivekananda",c:"perseverance",who:"Indian teacher"},
  {q:"Take up one idea. Make that one idea your life; dream of it.",a:"Swami Vivekananda",c:"dreams",who:"Indian teacher"},
  {q:"If you want to walk fast, walk alone. If you want to walk far, walk together.",a:"African Proverb",c:"teamwork",who:"a traditional saying"},
  {q:"Smooth seas do not make skillful sailors.",a:"African Proverb",c:"perseverance",who:"a traditional saying"},
  {q:"Knowledge is like a garden: if it is not cultivated, it cannot be harvested.",a:"African Proverb",c:"learning",who:"a traditional saying"},
  {q:"A single bracelet does not jingle.",a:"African Proverb",c:"teamwork",who:"a traditional saying"},
  {q:"When spider webs unite, they can tie up a lion.",a:"Ethiopian Proverb",c:"teamwork",who:"a traditional saying"},
  // ---- Poems & plays (public domain) with meaning + tappable hard words ----
  {c:"poetry",a:"William Shakespeare",who:"from Hamlet, Act 3 — a prince thinks aloud",
   q:"To be, or not to be, that is the question:\nWhether 'tis nobler in the mind to suffer\nThe slings and arrows of outrageous fortune,\nOr to take arms against a sea of troubles\nAnd by opposing end them. To die—to sleep,\nNo more; and by a sleep to say we end\nThe heart-ache and the thousand natural shocks\nThat flesh is heir to: 'tis a consummation\nDevoutly to be wish'd. To die, to sleep;\nTo sleep, perchance to dream—ay, there's the rub:\nFor in that sleep of death what dreams may come,\nWhen we have shuffled off this mortal coil,\nMust give us pause—there's the respect\nThat makes calamity of so long life.",
   m:"Hamlet is asking the biggest question of all: is it braver to keep living and face life's troubles, or to give up? He decides that what stops people from quitting is not knowing what comes next — so we keep going. It's really about facing hard times with courage.",
   hard:[{w:"nobler",d:"more honourable or brave; the finer, higher thing to do"},{w:"slings",d:"an old weapon that hurls stones — here it means life's hard knocks"},{w:"consummation",d:"the finishing or completing of something"},{w:"perchance",d:"an old word for 'maybe' or 'perhaps'"},{w:"rub",d:"the catch or the problem — the tricky part"},{w:"calamity",d:"a great misfortune or disaster"}]},
  {c:"poetry",a:"William Shakespeare",who:"Shylock, from The Merchant of Venice, Act 3",
   q:"I am a Jew. Hath not a Jew eyes? Hath not a Jew hands, organs, dimensions, senses, affections, passions; fed with the same food, hurt with the same weapons, subject to the same diseases, healed by the same means, warmed and cooled by the same winter and summer as a Christian is? If you prick us, do we not bleed? If you tickle us, do we not laugh? If you poison us, do we not die?",
   m:"Shylock is arguing that all people are the same underneath — we all feel pain, laughter and sadness. It's one of the most famous pleas in all of theatre for treating every person with fairness and kindness, no matter how different they seem.",
   hard:[{w:"dimensions",d:"the size and shape of a body — how big something is"},{w:"affections",d:"warm feelings of love or fondness for others"},{w:"passions",d:"very strong feelings or emotions"},{w:"prick",d:"to poke or jab with something sharp"},{w:"subject",d:"open to, or affected by, something"}]},
  {c:"poetry",a:"Robert Frost",who:"from 'The Road Not Taken'",
   q:"Two roads diverged in a wood, and I—\nI took the one less traveled by,\nAnd that has made all the difference.",
   m:"The poet reaches a fork in the path and chooses the road fewer people walk. It's a way of saying that making your own choices — even the harder, braver ones — can shape your whole life.",
   hard:[{w:"diverged",d:"split apart and went in two different directions"}]},
  {c:"poetry",a:"Emily Dickinson",who:"opening lines of a famous poem",
   q:"Hope is the thing with feathers\nThat perches in the soul,\nAnd sings the tune without the words,\nAnd never stops at all.",
   m:"Dickinson pictures hope as a little bird living inside us that keeps singing no matter what. Even in hard times, hope quietly keeps us going.",
   hard:[{w:"perches",d:"sits or rests, the way a bird settles on a branch"}]},
  {c:"poetry",a:"William Wordsworth",who:"from 'I Wandered Lonely as a Cloud'",
   q:"I wandered lonely as a cloud\nThat floats on high o'er vales and hills,\nWhen all at once I saw a crowd,\nA host, of golden daffodils.",
   m:"The poet, feeling alone, suddenly comes upon a huge field of dancing daffodils — and the simple beauty of nature fills him with joy. It reminds us to notice the small wonders around us.",
   hard:[{w:"vales",d:"valleys — low land between hills"},{w:"host",d:"a very large number or crowd of something"}]},
  {c:"poetry",a:"William Wordsworth",who:"poet of nature",
   q:"The world is too much with us; late and soon,\nGetting and spending, we lay waste our powers.",
   m:"Wordsworth warns that always chasing money and busywork can make us forget the beauty of nature and the things that really matter.",
   hard:[{w:"lay waste",d:"to ruin or use up carelessly"}]},
  // ---- Alexander Pope (master of the neat, memorable line) ----
  {c:"wisdom",a:"Alexander Pope",who:"English poet",q:"To err is human; to forgive, divine.",
   m:"Everybody makes mistakes — that's just being human. But choosing to forgive someone is a truly noble, God-like thing to do.",
   hard:[{w:"err",d:"to make a mistake or slip up"},{w:"divine",d:"heavenly or God-like; wonderfully good"}]},
  {c:"learning",a:"Alexander Pope",who:"English poet",q:"A little learning is a dangerous thing.",
   m:"Knowing just a tiny bit about something can fool you into thinking you know it all. Pope is nudging us to keep learning deeply, not stop halfway.",
   hard:[]},
  {c:"dreams",a:"Alexander Pope",who:"English poet",q:"Hope springs eternal in the human breast.",
   m:"No matter how hard things get, people always find fresh hope. Hope keeps bubbling up inside us, again and again.",
   hard:[{w:"eternal",d:"lasting forever; never ending"},{w:"breast",d:"the chest — here it means the heart or inner self"}]},
  {c:"friendship",a:"Alexander Pope",who:"English poet",q:"Blessed is the one who expects nothing, for they shall never be disappointed.",
   m:"If you don't demand things from others, you'll be pleasantly surprised instead of let down. A gentle, half-joking bit of wisdom.",
   hard:[]},
  // ---- Martin Luther King Jr. (the beauty of English used for justice) ----
  {c:"change",a:"Martin Luther King Jr.",who:"civil-rights leader",
   q:"I have a dream that my four little children will one day live in a nation where they will not be judged by the color of their skin but by the content of their character.",
   m:"In his most famous speech, Dr. King dreams of a fair world where people are valued for who they are inside — their character — not how they look. It became a rallying cry for equality.",
   hard:[{w:"content",d:"what is inside — the substance or true nature of something"},{w:"character",d:"the kind of person you are: your honesty, kindness and courage"}]},
  {c:"kindness",a:"Martin Luther King Jr.",who:"civil-rights leader",
   q:"Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.",
   m:"You can't fix cruelty with more cruelty. Only kindness and love can truly push out hatred — just as only light can chase away the dark.",
   hard:[{w:"drive out",d:"to force away or get rid of"}]},
  {c:"honesty",a:"Martin Luther King Jr.",who:"civil-rights leader",q:"The time is always right to do what is right.",
   m:"There's never a wrong moment to do the right thing. If something is good and fair, do it now — don't wait.",hard:[]},
  {c:"believe",a:"Martin Luther King Jr.",who:"civil-rights leader",
   q:"Faith is taking the first step even when you don't see the whole staircase.",
   m:"You don't need to see how everything will work out to begin. Have courage, take that first step, and trust the rest will follow.",hard:[]},
  {c:"perseverance",a:"Martin Luther King Jr.",who:"civil-rights leader",
   q:"If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward.",
   m:"However slowly you have to go, never stop making progress. Any step forward, no matter how small, still counts.",hard:[]}
]);


