/* Bizzing Bee — story arc data (all 15 packs). Authored in Claude Design
   (avatar-redesign/story-arcs-data.js + story-arcs-data2.js), imported verbatim.
   Shape: { pack, accent, ink, title, log, beats:[{t,x,c:[ids]}], cast:[{id,n,r,a,f}] } */
window.SB_STORY_ARCS = (window.SB_STORY_ARCS || []).concat([

{ pack: "Hive Pack", accent: "#FFC23D", ink: "#7A4A08", title: "The Silent Meadow",
  log: "One morning the Hummingbird Meadow goes quiet — every flower shut tight, honey running low. The Queen sends Bizzy and friends to wake the First Flower before the Honey Moon festival.",
  beats: [
    { t: "The Quiet Morning", x: "The meadow wakes silent, every flower shut. The Queen unrolls the wax map and gives Bizzy the quest.", c: ["bizzy","queenhive"] },
    { t: "The Crew Assembles", x: "Honey Pot packs the emergency jar, Drone Dan rigs the leaf-glider, Nectar fuels every wing — Bumble carries the rest.", c: ["honeypot","drone","nectar","bumble"] },
    { t: "The Waggle Map", x: "Where the wax runs out, Waggle dances the missing directions; Clover calls the lucky fork.", c: ["waggle","clover"] },
    { t: "Bramble Gate", x: "Propolis holds the thorns on the hexagon shield while Blossom sweet-talks the roses aside.", c: ["propolis","blossom"] },
    { t: "The First Flower", x: "Bizzy shares the last drop of honey; the Flower blooms gold and the meadow wakes. The Queen crowns the Wing Guard.", c: ["bizzy","honeypot","queenhive"] } ],
  cast: [
    { id: "bizzy", n: "Bizzy Bee", r: "The Hero", a: "Takes the Queen’s quest — and it’s Bizzy’s shared last drop that wakes the First Flower.", f: "Bees recognize human faces." },
    { id: "queenhive", n: "Hive Queen", r: "The Mentor", a: "Unrolls the wax map to start the quest, and crowns the crew the Wing Guard at the finale.", f: "A queen bee lays up to 2,000 eggs a day." },
    { id: "honeypot", n: "Honey Pot", r: "The Heart", a: "Packs the “emergencies only” jar — the drop of gold that saves the meadow.", f: "Honey never spoils — 3,000-year-old honey is still edible." },
    { id: "drone", n: "Drone Dan", r: "The Builder", a: "Rigs the leaf-glider that carries the crew past the meadow’s edge.", f: "Drone bees have no stinger at all." },
    { id: "nectar", n: "Nectar", r: "The Fuel", a: "Tops up every wing with one golden drop before the journey begins.", f: "One jar of honey = about two million flower visits." },
    { id: "bumble", n: "Bumble", r: "The Muscle", a: "Shrugs, says “I’ll carry the heavy stuff,” then carries the crew through the wind too.", f: "Bumblebees “shouldn’t” fly by old airplane math. They flap 200×/sec anyway." },
    { id: "waggle", n: "Waggle", r: "The Navigator", a: "Dances the missing half of the map when the wax runs out.", f: "The waggle dance is a real map — bees dance directions to flowers." },
    { id: "clover", n: "Clover", r: "The Lucky Scout", a: "Calls “left is lucky today” at the fork — and is right, as always.", f: "Only 1 in 10,000 clovers has four leaves." },
    { id: "propolis", n: "Propolis", r: "The Shield", a: "Plants the hexagon shield at Bramble Gate and holds the thorns back.", f: "Hexagons are nature’s strongest shape for the least material." },
    { id: "blossom", n: "Blossom", r: "The Flower-Whisperer", a: "Speaks softly in flower until the roses curl their thorns aside.", f: "Sunflowers turn their heads to follow the sun all day." } ] },

{ pack: "Stage Pack", accent: "#9C6A08", ink: "#5C3A08", title: "Opening Night",
  log: "One hour before the biggest show of the year, every light in the Grand Meadow Theatre goes dark.",
  beats: [
    { t: "Blackout", x: "One hour to curtain, the theatre goes dark. Center Star refuses to cancel; Lumen is down to a single bulb.", c: ["star","lumen"] },
    { t: "Rescored", x: "Maestro rewrites the whole show for darkness while Big Mic warms up to carry it on voice alone.", c: ["maestro","mic"] },
    { t: "Stalling the Crowd", x: "Jester works the aisles and Popcorn passes snacks down the rows — the wait becomes a warm-up act.", c: ["jester","popcorn"] },
    { t: "One Last Number", x: "Diva comes out of retirement for a single song; Melody writes it live on a ticket stub.", c: ["diva","melody"] },
    { t: "The Candlelight Finale", x: "Lumen’s one beam through the mirror ball, Encore’s chant shaking the rafters — Gold Legend leads the standing ovation.", c: ["lumen","encore","goldlegend","star"] } ],
  cast: [
    { id: "star", n: "Center Star", r: "The Headliner", a: "Refuses to cancel and holds the stage together when the lights die.", f: "“Break a leg” means good luck — saying “good luck” is the jinx." },
    { id: "mic", n: "Big Mic", r: "The Voice", a: "Carries the whole show on sound alone while the stage is dark.", f: "Your voice is as unique as your fingerprint." },
    { id: "maestro", n: "Maestro", r: "The Conductor", a: "Rescores the entire show for darkness in one frantic hour.", f: "An orchestra tunes to one single note: A." },
    { id: "jester", n: "Jester", r: "The Distraction", a: "Keeps the restless crowd laughing while the crew scrambles backstage.", f: "Court jesters were the only people allowed to joke about the king." },
    { id: "lumen", n: "Lumen the Light", r: "The Light", a: "Down to one bulb, reroutes its beam through the mirror ball for the finale.", f: "“Limelight” was real — old stages burned lime rock for light." },
    { id: "diva", n: "Diva", r: "The Legend", a: "Retired for years — says yes to one last number when it matters most.", f: "Opera singers can shatter glass with the right note." },
    { id: "popcorn", n: "Popcorn", r: "The Crowd’s Heart", a: "Passes snacks down the rows and turns waiting into a party.", f: "Popping corn can jump almost a metre in the air." },
    { id: "melody", n: "Melody", r: "The Song", a: "Writes the finale number live, on the back of a ticket stub.", f: "Songs stuck in your head are called earworms." },
    { id: "encore", n: "Encore", r: "The Superfan", a: "Starts the “one more!” chant that becomes the loudest moment of the year.", f: "“Encore” is French for “again!”" },
    { id: "goldlegend", n: "Gold Legend", r: "The Prize", a: "Watches from the judges’ box — and gives the night a standing ovation.", f: "Most “gold” trophies are gold-plated — the shine is microns thick." } ] },

{ pack: "Cosmos Pack", accent: "#4A5BD4", ink: "#1E2A5C", title: "The Missing Star",
  log: "One star in the Great Dipper blinks out — and only the Cosmos crew notices.",
  beats: [
    { t: "The Hole in the Sky", x: "Luna can’t sleep: the Dipper is missing a star.", c: ["luna"] },
    { t: "Launch Window", x: "Rocket Rae counts down, Astro rides shotgun, Comet takes the tow line.", c: ["rocket","astro","comet"] },
    { t: "The Shortcut", x: "Zib knows a way through the asteroid field; Saturn slings the crew around its rings for speed.", c: ["alien","saturn"] },
    { t: "The Lonely Dark", x: "They find Void holding the borrowed starlight. Supernova shows the brightest thing to do with light: share it.", c: ["blackhole","supernova"] },
    { t: "Rehung and Burning", x: "Saucer beams the star home; Nebula Drake breathes stardust so the sky never dims again.", c: ["ufo","nebula"] } ],
  cast: [
    { id: "luna", n: "Luna", r: "The Watcher", a: "First to notice the hole in the sky where a star should be.", f: "The Moon drifts 4 cm farther from Earth every year." },
    { id: "astro", n: "Astro", r: "The Pilot", a: "Suits up for the rescue and never lets go of the tow line.", f: "Astronauts grow up to 5 cm taller in space." },
    { id: "comet", n: "Comet", r: "The Ride", a: "Tows the crew across three constellations at full blaze.", f: "A comet’s tail always points away from the Sun." },
    { id: "rocket", n: "Rocket Rae", r: "The Launch", a: "Counts down from ten and means it.", f: "Space is only an 8-minute rocket ride away." },
    { id: "alien", n: "Zib the Alien", r: "The Local", a: "Knows the shortcut through the asteroid field (“trust me”).", f: "There are more stars than grains of sand on every beach on Earth." },
    { id: "saturn", n: "Saturn", r: "The Slingshot", a: "Spins the crew around its rings for a gravity boost.", f: "Saturn is so light it would float in a (very big) bathtub." },
    { id: "blackhole", n: "Void", r: "The Misunderstood", a: "Borrowed the star’s light because the dark was lonely — and gives it back.", f: "Near a black hole, time itself runs slower." },
    { id: "supernova", n: "Supernova", r: "The Example", a: "Shows Void that the brightest thing you can do with light is share it.", f: "The gold in every ring on Earth was forged in exploding stars." },
    { id: "ufo", n: "Saucer", r: "The Lift Home", a: "Beams the star gently back into its constellation.", f: "A day on Venus lasts longer than its whole year." },
    { id: "nebula", n: "Nebula Drake", r: "The Guardian", a: "Breathes stardust over the sky so it never goes dim again.", f: "Nebulas are star nurseries — new suns are being born right now." } ] },

{ pack: "Dojo Pack", accent: "#C43D5A", ink: "#6E1F30", title: "The Silent Bell",
  log: "The dojo’s ancient bell has never rung. Legend says only true calm can ring it.",
  beats: [
    { t: "The Trial", x: "Panda Sensei announces it: ring the bell that has never rung. Then says nothing else all week.", c: ["panda"] },
    { t: "Speed Fails", x: "Shadow Ninja and Star Steel strike faster than sight. Not a wobble.", c: ["ninja","starsteel"] },
    { t: "Strength Fails", x: "Samurai and Oni bring full power; Bamboo grows a ladder to look for a crack. There isn’t one.", c: ["samurai","oni","bamboo"] },
    { t: "The Secret", x: "Koi climbs the waterfall for the bell’s old instructions; Kitsune translates the trick — stillness, not strikes.", c: ["koi","kitsune"] },
    { t: "One Breath", x: "Lucky Neko’s slow blink settles the room; Dragon Master hums one low note — and the bell rings itself.", c: ["neko","dragonmaster","panda"] } ],
  cast: [
    { id: "panda", n: "Panda Sensei", r: "The Sensei", a: "Announces the trial of the Silent Bell — and says nothing else all week.", f: "Pandas spend 12 hours a day eating." },
    { id: "ninja", n: "Shadow Ninja", r: "The Fastest", a: "Strikes quicker than sight; the bell doesn’t even wobble.", f: "Real ninjas’ best weapon was dressing like ordinary farmers." },
    { id: "samurai", n: "Samurai", r: "The Strongest", a: "Full armor, full power — the bell stays silent.", f: "Samurai armor was built from hundreds of tiny lacquered plates." },
    { id: "neko", n: "Lucky Neko", r: "The Calm", a: "One slow blink starts the stillness that finally rings the bell.", f: "The waving cat statue is a 400-year-old good-luck charm." },
    { id: "bamboo", n: "Bamboo", r: "The Ladder", a: "Grows a metre in a day so the crew can inspect the bell up close.", f: "Bamboo can grow almost a metre in a single day." },
    { id: "kitsune", n: "Kitsune", r: "The Trickster", a: "Reveals the trick: the bell rings for stillness, not strikes.", f: "In legend, fox spirits earn a new tail every 100 years." },
    { id: "oni", n: "Oni Grin", r: "The Grinner", a: "Tries scaring the bell into ringing. It does not work. Great grin though.", f: "Oni masks are worn to scare bad luck away — not people." },
    { id: "koi", n: "Koi", r: "The Climber", a: "Climbs the waterfall to fetch the bell’s ancient instructions.", f: "Legend says a koi that climbs the waterfall becomes a dragon." },
    { id: "starsteel", n: "Star Steel", r: "The Precise", a: "Throws a perfect spinning strike — a distraction, as always.", f: "Throwing stars were mostly for distraction — the escape was the real move." },
    { id: "dragonmaster", n: "Dragon Master", r: "The Master", a: "Hums one low note as the whole dojo sits still — and the bell answers.", f: "Eastern dragons don’t breathe fire — they bring rain and luck." } ] },

{ pack: "Lab Pack", accent: "#0E8A78", ink: "#0F3A34", title: "The Great Fizz",
  log: "Every bubble in the lab goes flat the week of the science fair. The fizz must be found.",
  beats: [
    { t: "Flat", x: "Bubbly Beaker wakes without a single bubble. Lab-wide fizz emergency, five days to the fair.", c: ["beaker"] },
    { t: "Diagnosis", x: "Atom counts particles while Scopey zooms in: the molecules aren’t gone. They’re asleep.", c: ["atom","scopey"] },
    { t: "The Wake-Up", x: "Magneto Max pulls them into line, Robo dials it in, Volt delivers the jolt.", c: ["magnet","robo","volt"] },
    { t: "The Happy Accident", x: "Germy’s forgotten “mistake” is the missing catalyst — Brainiac connects it in a flash.", c: ["germy","brainiac"] },
    { t: "Golden Fizz", x: "Phoenix relights the burner and Aurum pours the demo: the fair’s first standing ovation for a drink.", c: ["phoenix","aurum"] } ],
  cast: [
    { id: "beaker", n: "Bubbly Beaker", r: "The First Sign", a: "Wakes up flat — not one bubble — and raises the alarm.", f: "Soda fizz is a gas escaping — CO₂ making a run for it." },
    { id: "atom", n: "Atom", r: "The Physicist", a: "Checks every particle twice; the fizz isn’t gone, it’s asleep.", f: "You’re made of about 7 octillion atoms." },
    { id: "robo", n: "Robo Helper", r: "The Calibrator", a: "Runs the numbers and points every dial at “wake up”.", f: "The word “robot” comes from a Czech word for “work”." },
    { id: "magnet", n: "Magneto Max", r: "The Pull", a: "Drags the sleepy molecules back into line.", f: "Earth itself is a giant magnet — that’s how compasses work." },
    { id: "germy", n: "Germy", r: "The Happy Accident", a: "Its “mistake” culture turns out to be the missing catalyst.", f: "You carry more bacteria cells than human cells. Mostly friendly." },
    { id: "brainiac", n: "Brainiac", r: "The Connector", a: "Sees the pattern between the mistake and the fix.", f: "Your brain runs on about as much power as a lightbulb." },
    { id: "phoenix", n: "Phoenix Flame", r: "The Spark", a: "Relights the master burner in one bright beat.", f: "Fire in space burns as a floating blue sphere." },
    { id: "volt", n: "Volt", r: "The Charge", a: "Delivers the jolt that restarts the reaction.", f: "Lightning is five times hotter than the surface of the Sun." },
    { id: "scopey", n: "Scopey", r: "The Eyes", a: "Zooms in and finds the molecules snoozing mid-fizz.", f: "A single drop of pond water is a whole city of tiny creatures." },
    { id: "aurum", n: "Aurum Formula", r: "The Formula", a: "The golden fizz itself — pours the winning demo at the fair.", f: "Gold’s symbol is Au — and all of it came from space." } ] },

{ pack: "Arcade Pack", accent: "#3B6FE0", ink: "#12234A", title: "Insert Coin",
  log: "The arcade closes tomorrow — and its master cabinet has one unbeaten final level.",
  beats: [
    { t: "Last Token", x: "The arcade closes tomorrow. Tokeny volunteers; Pixel steps up to the master cabinet.", c: ["tokeny","pixel"] },
    { t: "Co-op Mode", x: "Joy takes the stick, D-Pad the directions — and Cabinet Ghost coaches from inside the machine.", c: ["joy","dpad","ghost"] },
    { t: "The Warp Route", x: "Glitch shears open the hidden warp; Rainbow Cart drifts the lap nobody’s cleared.", c: ["glitch","rainbow"] },
    { t: "Boss Fight", x: "Boss Bot, full health bar, final form. 1-UP calls the pattern from memory.", c: ["bossbot","hiscore"] },
    { t: "High Score", x: "The final screen falls, the marquee blazes — Neon King lights a line around the block. Arcade saved.", c: ["neonking","pixel"] } ],
  cast: [
    { id: "pixel", n: "Pixel Pal", r: "The Player One", a: "Steps up with the arcade’s very last token in hand.", f: "“Pixel” is short for picture element." },
    { id: "joy", n: "Joy Stick", r: "The Controls", a: "Takes the joystick for the co-op run of a lifetime.", f: "Esports finals sell out whole stadiums." },
    { id: "ghost", n: "Cabinet Ghost", r: "The Insider", a: "Haunts the cabinet — knows every hidden wall from the inside.", f: "The first computer “bug” was a real moth stuck in the machine." },
    { id: "dpad", n: "D-Pad", r: "The Combos", a: "Inputs the 40-year-old code at exactly the right frame.", f: "Up, up, down, down… the most famous cheat code is 40 years old." },
    { id: "tokeny", n: "Tokeny", r: "The Last Coin", a: "Rolls itself into the slot. No pressure.", f: "Old arcade tokens were made worthless outside the arcade on purpose." },
    { id: "bossbot", n: "Boss Bot", r: "The Final Boss", a: "Full health bar, smug grin — falls to teamwork on the last life.", f: "“Boss” fights are named for the toughest enemy guarding the end." },
    { id: "rainbow", n: "Rainbow Cart", r: "The Impossible Lap", a: "Drifts the warp-zone track nobody’s ever cleared.", f: "Racing games taught real F1 drivers their first tracks." },
    { id: "glitch", n: "Glitch", r: "The Warp", a: "Opens the hidden route that skips the unwinnable level.", f: "Some famous game moves started life as glitches players kept." },
    { id: "hiscore", n: "1-UP", r: "The Coach", a: "Calls the boss pattern from memory: up, up, down, down…", f: "The top arcade scores ever set took days of nonstop play." },
    { id: "neonking", n: "Neon King", r: "The Marquee", a: "Lights the sign so bright the whole town comes to watch.", f: "Neon signs glow because electricity makes the gas itself light up." } ] },

{ pack: "Origami Pack", accent: "#C25A2E", ink: "#6E3418", title: "One Thousand Folds",
  log: "The paper kingdom is unfolding — creases fading everywhere. Only the 1,000th crane can re-crease the world.",
  beats: [
    { t: "The Unfolding", x: "Mid-flight, Paper Plane feels its wings going soft — creases are fading kingdom-wide.", c: ["paperplane"] },
    { t: "Nine Hundred Ninety-Nine", x: "Crane has counted every crane ever folded. One more grants the wish.", c: ["cranefold"] },
    { t: "The Ink River", x: "Little Boat ferries the crew, Hop Frog leaps the faded gaps, Fan Dancer holds off the unfolding wind.", c: ["boatfold","hopfold","fanfold"] },
    { t: "The Pattern", x: "Lotus remembers the sequence, Koi runs it upstream, Kabuto guards the last sheet, Flutter delivers it.", c: ["lotusfold","koifold","kabuto","flutterfold"] },
    { t: "The Thousandth Crane", x: "One sheet, no cuts, no glue — and every crease in the kingdom snaps sharp. The Golden Crane rises.", c: ["goldencrane"] } ],
  cast: [
    { id: "paperplane", n: "Paper Plane", r: "The Scout", a: "First to feel the folds going soft mid-flight.", f: "The world-record paper plane flew 88 metres." },
    { id: "cranefold", n: "Crane", r: "The Keeper", a: "Has counted every crane ever folded: 999. One to go.", f: "Fold 1,000 cranes and legend grants you a wish." },
    { id: "boatfold", n: "Little Boat", r: "The Ferry", a: "Sails the crew down the ink river to the last sheet.", f: "Paper can’t be folded in half more than about 7 times." },
    { id: "hopfold", n: "Hop Frog", r: "The Leap", a: "Jumps the gaps in the map where the creases faded.", f: "A real origami frog jumps when you press its back fold." },
    { id: "fanfold", n: "Fan Dancer", r: "The Windbreak", a: "Pleats wide open to hold back the wind that unfolds things.", f: "Accordion folds make paper strong enough to stand on." },
    { id: "lotusfold", n: "Lotus", r: "The Memory", a: "Meditates the thousand-fold sequence back into being.", f: "Real lotus flowers heat themselves like tiny radiators." },
    { id: "koifold", n: "Paper Koi", r: "The Current", a: "Carries the fold pattern upstream, stripes flashing.", f: "Origami folds now unfold satellites and heart stents." },
    { id: "kabuto", n: "Kabuto", r: "The Guard", a: "Stands over the kingdom’s last uncut sheet.", f: "Kids in Japan fold kabuto helmets every Children’s Day." },
    { id: "flutterfold", n: "Flutter", r: "The Courier", a: "Delivers the pattern on patterned wings, loop-the-loop.", f: "Butterflies taste with their feet." },
    { id: "goldencrane", n: "Golden Crane", r: "The Thousandth", a: "The wish itself: every crease in the kingdom sharp again.", f: "One sheet, no cuts, no glue — the crane is pure geometry." } ] },

{ pack: "Elements Pack", accent: "#2E8FB8", ink: "#123A52", title: "Four-Season Tuesday",
  log: "The seasons jam and all four arrive at once. Snow on the sunflowers. Someone has to restore turns.",
  beats: [
    { t: "The Pileup", x: "Snow on the sunflowers, a heatwave on the ice rink. Pebble sits through all of it, concerned.", c: ["pebble"] },
    { t: "Scouting the Jam", x: "Breeze rides the jetstream up; Cloudy reports the pileup from above.", c: ["breeze","cloudy"] },
    { t: "The Argument", x: "Fire and water are quarreling over whose turn it is. Droplet and Ember speak for each side; Leafy translates.", c: ["droplet","ember","leafy"] },
    { t: "Cooler Heads", x: "Big Wave cools tempers, Boulder holds the middle ground, Zappy restarts the sky’s rhythm.", c: ["wave","boulder","zappy"] },
    { t: "Taking Turns", x: "Elemental Prime conducts all four back into order: spring, then summer, then fall, then snow.", c: ["elemental"] } ],
  cast: [
    { id: "pebble", n: "Pebble", r: "The Steady", a: "Sits through all four seasons at once, entirely unbothered.", f: "Every pebble you pick up is millions of years old." },
    { id: "breeze", n: "Breeze", r: "The Messenger", a: "Rides the jetstream to find where the seasons jammed.", f: "Wind is just air racing from crowded space to empty space." },
    { id: "droplet", n: "Droplet", r: "Water’s Voice", a: "Speaks for water in the fire-and-water argument.", f: "The water you drank today was once sipped by dinosaurs." },
    { id: "ember", n: "Ember", r: "Fire’s Voice", a: "Speaks for fire — mostly in sparks.", f: "The hottest part of a flame is the part you can barely see." },
    { id: "leafy", n: "Leafy", r: "The Translator", a: "Turns wind, water and fire talk into one language.", f: "Trees share food and messages through their roots." },
    { id: "cloudy", n: "Cloudy", r: "The Lookout", a: "Reports the four-season pileup from above (while raining slightly).", f: "An average cloud weighs about as much as 100 elephants." },
    { id: "wave", n: "Big Wave", r: "The Cool-Down", a: "Rolls in to cool tempers when the argument gets hot.", f: "Ocean waves can travel across the whole planet." },
    { id: "boulder", n: "Boulder", r: "The Anchor", a: "Holds the middle ground. Literally.", f: "Mountains grow — Everest gets a little taller every year." },
    { id: "zappy", n: "Zappy", r: "The Restart", a: "One precise bolt restarts the sky’s rhythm.", f: "Lightning strikes Earth about 100 times every second." },
    { id: "elemental", n: "Elemental Prime", r: "The Conductor", a: "Brings all four elements back into taking turns.", f: "Ancient scientists thought earth, air, fire and water were the whole universe." } ] },

{ pack: "Critter Crew", accent: "#E8845C", ink: "#5C2A10", title: "The Big Splash",
  log: "The pond is dropping an inch a day. Upriver, something is blocking the water.",
  beats: [
    { t: "Low Tide", x: "Pond Star’s lily pad touches mud. That has never happened.", c: ["froggy"] },
    { t: "The Zoom", x: "Zoomies runs word to every burrow; Slowmo departs at once (ETA Thursday).", c: ["corg","slowmo"] },
    { t: "The Log Jam", x: "Finn scouts the river and finds it: a log jam. Narly starts picking it apart, tusk-first.", c: ["sharky","narly"] },
    { t: "Team Lift", x: "Rusty stands tall for morale, Rexy brings the bite, Capy talks the resident beaver into helping, Axo forgives a nipped tail.", c: ["redpanda","rexy","capy","axo"] },
    { t: "The Splash", x: "The river lets go all at once. Uni arcs a rainbow over the refilled pond. Slowmo arrives. Perfect timing.", c: ["uni","slowmo","froggy"] } ],
  cast: [
    { id: "froggy", n: "Pond Star", r: "The First Alarm", a: "Wakes with the lily pad touching mud and sounds the alarm.", f: "Frogs drink through their skin — no sipping required." },
    { id: "corg", n: "Zoomies", r: "The Messenger", a: "Zooms the news to every burrow before breakfast.", f: "Corgis were bred to herd cattle — by nipping ankles." },
    { id: "sharky", n: "Finn", r: "The Scout", a: "Swims upriver in sunglasses to find the blockage.", f: "Sharks are older than trees — by 50 million years." },
    { id: "slowmo", n: "Slowmo", r: "The Long Game", a: "Starts helping immediately; arrives Thursday.", f: "Sloths swim three times faster than they walk." },
    { id: "narly", n: "Narly", r: "The Toolkit", a: "Picks the log jam apart tusk-first, one twig at a time.", f: "A narwhal’s tusk is a giant tooth with ten million nerve endings." },
    { id: "redpanda", n: "Rusty", r: "The Big & Scary", a: "Stands tall at the jam. It mostly looks adorable. It helps morale.", f: "Red pandas stand up to look bigger — it mostly looks cute." },
    { id: "capy", n: "Capy", r: "The Negotiator", a: "Calms the grumpy beaver into lending a paw.", f: "Capybaras are so calm every animal wants to sit with them." },
    { id: "axo", n: "Axo", r: "The Good Sport", a: "Gets a tail nipped in the chaos, regrows it, holds no grudge.", f: "Axolotls can regrow legs, tails, even parts of their heart." },
    { id: "rexy", n: "Rexy", r: "The Bite", a: "The strongest bite in the valley finally gets a job worth doing.", f: "T. rex had the strongest bite of any land animal ever." },
    { id: "uni", n: "Uni", r: "The Promise", a: "Arcs a rainbow over the refilled pond — rain will come when needed.", f: "The unicorn is the official national animal of Scotland." } ] },

{ pack: "Vibe Pack", accent: "#8A5CE8", ink: "#2E1B52", title: "The Sleepover",
  log: "The ultimate Friday sleepover — until the power goes out at 8:03pm.",
  beats: [
    { t: "8:03pm", x: "Mid-match, the screen dies. Whole block dark. GG calls it: “best sleepover ever starts now.”", c: ["gg"] },
    { t: "Snack Protocol", x: "Boba leads the kitchen raid by phone-light, Sprinkle supplies emergency donuts, Duckie supervises in silence.", c: ["boba","sprinkle","duckie"] },
    { t: "Unplugged", x: "Beat Bot’s battery holds a dance party; Slimey becomes the nightlight; Pengu invents hallway belly-sliding.", c: ["djbot","slimey","pengu"] },
    { t: "Big Feelings", x: "Someone misses home. Plushy handles it. Catlord pretends not to care from exactly one metre away.", c: ["plushy","catlord"] },
    { t: "Snow Day", x: "Power returns at dawn — and the windows are white. Frost was busy all night.", c: ["yeti"] } ],
  cast: [
    { id: "gg", n: "GG", r: "The Cool Head", a: "Screen dies mid-match; calls “GG” and starts the best night ever.", f: "“GG” — good game — is the oldest rule of good sportsmanship online." },
    { id: "duckie", n: "Duckie", r: "The Supervisor", a: "Oversees the snack raid by phone-light. Says nothing. Sees everything.", f: "Scientists mapped ocean currents using 28,000 rubber ducks lost at sea." },
    { id: "boba", n: "Boba", r: "The Snack Run", a: "Leads the kitchen expedition, pearls first.", f: "Boba pearls are tapioca — they come from a root." },
    { id: "sprinkle", n: "Sprinkle", r: "The Sugar", a: "Provides the emergency donuts. Kickflips one. Sticks it.", f: "The donut hole was invented so they’d cook evenly." },
    { id: "pengu", n: "Pengu", r: "The Slide", a: "Turns the dark hallway into a belly-slide speedrun.", f: "Penguins propose with a pebble." },
    { id: "slimey", n: "Slimey", r: "The Nightlight", a: "Glows in the dark — becomes the most important friend in the house.", f: "Slime is solid when you punch it, liquid when you don’t." },
    { id: "djbot", n: "Beat Bot", r: "The Playlist", a: "Battery full, one headphone up — unplugged dance party, delivered.", f: "Every digital song is secretly just numbers played very fast." },
    { id: "plushy", n: "Plushy", r: "The Comfort", a: "Finds the one who misses home and does the only job that matters.", f: "Hugging something soft genuinely lowers stress — it’s science." },
    { id: "catlord", n: "Catlord", r: "The Softie", a: "Pretends not to care about any of it; stays within one metre all night.", f: "Cats can’t taste sweet things. They don’t care." },
    { id: "yeti", n: "Frost", r: "The Surprise", a: "Was outside all night — dawn reveals why: it snowed, everywhere.", f: "The yeti has been “spotted” for centuries — never photographed clearly." } ] },

{ pack: "Dino Pack", accent: "#6CB454", ink: "#2B4A1E", title: "The Rumble Egg",
  log: "A mystery egg appears in the valley. Every dino has a theory. None of them are right.",
  beats: [
    { t: "The Egg", x: "Trice finds a mystery egg and goes full frill-shield around it.", c: ["trice"] },
    { t: "Theories", x: "Stego says it’s “definitely a stego” (it is not). Bronto keeps high watch; Ptero sweeps the skies for the parents.", c: ["stego","bronto","ptero"] },
    { t: "The Search", x: "Raptor tracks old prints, Spino checks every river, Ankylo clears the rockslide to the nesting cliffs.", c: ["raptor","spino","ankylo"] },
    { t: "Night Watch", x: "Fossil glows over the egg through the cold; Mosa guards the shoreline.", c: ["fossil","mosa"] },
    { t: "Hatch Day", x: "A tiny rex! Rex King arrives at dawn — and bows a king’s thanks to the whole valley.", c: ["rexking","trice"] } ],
  cast: [
    { id: "trice", n: "Trice", r: "The Finder", a: "Finds the mystery egg and goes full frill-shield around it.", f: "A Triceratops frill could grow bigger than a car door." },
    { id: "stego", n: "Stego", r: "The Debater", a: "Insists the egg is “definitely a stego”. (It is not.)", f: "Stegosaurus ran on a brain the size of a walnut — and did fine." },
    { id: "raptor", n: "Raptor", r: "The Tracker", a: "Follows week-old footprints across three riverbeds.", f: "Real raptors were turkey-sized — and covered in feathers." },
    { id: "ptero", n: "Ptero", r: "The Air Search", a: "Sweeps the skies looking for the egg’s parents.", f: "Pterosaurs weren’t dinosaurs — some had wings wider than a bus." },
    { id: "bronto", n: "Bronto", r: "The High View", a: "Keeps a neck-level watch over the whole valley.", f: "A Brontosaurus neck was longer than a school bus." },
    { id: "spino", n: "Spino", r: "The River Route", a: "Checks every waterway a nest could have washed from.", f: "Spinosaurus is the only dinosaur we know could swim." },
    { id: "ankylo", n: "Ankylo", r: "The Roadcrew", a: "Clears the rockslide between the valley and the nesting cliffs.", f: "An Ankylosaurus tail club could break a T. rex’s leg." },
    { id: "mosa", n: "Mosa", r: "The Shore Watch", a: "Guards the coastline so nothing surprises the egg by sea.", f: "Mosasaurus was 15 metres of real sea monster." },
    { id: "fossil", n: "Fossil", r: "The Night Light", a: "Glows green over the egg through the cold nights.", f: "Dragon legends likely began when people dug up dinosaur bones." },
    { id: "rexking", n: "Rex King", r: "The Answer", a: "Arrives on hatch day — and bows a king’s thanks for minding the little rex.", f: "No land animal ever bit harder than T. rex." } ] },

{ pack: "Enchanted Pack", accent: "#A05CC8", ink: "#44205C", title: "The Borrowed Moon",
  log: "One week before the Star Festival, the moon doesn’t rise.",
  beats: [
    { t: "The Moonless Night", x: "The moon doesn’t rise. Midnight’s crescent collar won’t stop glowing.", c: ["midnight"] },
    { t: "Follow the Lights", x: "Wisp leads the way (honestly, for once); Luna Moth steers by the memory of moonlight.", c: ["wisp","lunamoth"] },
    { t: "The Fairy Ring", x: "Fae trades three good jokes for passage; Crystal bends the last stray moonbeam into a trail.", c: ["fae","crystal"] },
    { t: "The Sleeping Moon", x: "Pearl finds it asleep on the seafloor. Snowfox lights the deep, Briar weaves a thorn-stair, Wish carries the wake-up call.", c: ["mer","snowfox","briar","wish"] },
    { t: "Rehung", x: "Starweaver threads the moon back into the sky — one night before the Star Festival.", c: ["starweaver"] } ],
  cast: [
    { id: "midnight", n: "Midnight", r: "The First to Know", a: "A moonless night — and a crescent collar that won’t stop glowing.", f: "To sailors, black cats were good luck — kept aboard to protect the ship." },
    { id: "wisp", n: "Wisp", r: "The Guide", a: "Offers to lead the way — and for once, leads honestly.", f: "Will-o’-wisps were real — glowing marsh gas that led travellers astray." },
    { id: "lunamoth", n: "Luna Moth", r: "The Compass", a: "Navigates by the memory of moonlight alone.", f: "Luna moths live one week and never eat — they don’t have a mouth." },
    { id: "fae", n: "Fae", r: "The Bargainer", a: "Trades three good jokes at the fairy ring for safe passage.", f: "Fairy rings are real — mushrooms growing in circles, some centuries old." },
    { id: "crystal", n: "Crystal", r: "The Lens", a: "Bends the last stray moonbeam into a trail to follow.", f: "Crystals build themselves atom by atom — some took millions of years." },
    { id: "mer", n: "Pearl", r: "The Deep Search", a: "Finds the moon asleep on the seafloor, tucked in kelp.", f: "Sailors’ “mermaid sightings” were probably manatees." },
    { id: "snowfox", n: "Snowfox", r: "The Fox-Fire", a: "Lights the deep water with aurora sparks from its tail.", f: "Finnish legend says auroras are sparks from a fox’s tail — “fox fires”." },
    { id: "briar", n: "Briar", r: "The Ladder", a: "Weaves a thorn-stair down to the sleeping moon (mind the prickles).", f: "Rose “thorns” are technically called prickles." },
    { id: "wish", n: "Wish", r: "The Wake-Up Call", a: "Streaks past the moon carrying everyone’s wish: “come home.”", f: "Most “shooting stars” are dust the size of a grain of rice." },
    { id: "starweaver", n: "Starweaver", r: "The Rehanging", a: "Weaves the moon back into the night in time for the festival.", f: "Every culture drew different pictures with the same stars." } ] },

{ pack: "Wildhearts Pack", accent: "#E86A9A", ink: "#5C1F38", title: "The Long Way Home",
  log: "A first-year Monarch must fly 4,800 km to a forest she’s never seen. The meadow walks her out.",
  beats: [
    { t: "The Pull South", x: "Monarch feels it: 4,800 km to a forest she’s never seen. Leaving day.", c: ["monarch"] },
    { t: "The Send-Off", x: "Hoppy binkies the goodbye; Fawn walks her to the meadow’s edge, silent and unseen.", c: ["hoppy","fawn"] },
    { t: "The River", x: "Ottie ferries her across on his belly; Echo calls the one safe channel through the rapids.", c: ["ottie","echo"] },
    { t: "The Storm", x: "Swan opens a wing over her; Howl’s pack sings a beacon; Pounce snatches the wind-stolen map out of the air.", c: ["swan","howl","pounce"] },
    { t: "Arrival", x: "Blaze runs the last valley beside her — and Pegasus stamps a spring where she lands.", c: ["blaze","pegasus"] } ],
  cast: [
    { id: "monarch", n: "Monarch", r: "The Traveler", a: "Feels the pull south to a forest she has never seen — and goes.", f: "Monarchs fly 4,800 km to a forest they have never seen." },
    { id: "hoppy", n: "Hoppy", r: "The Send-Off", a: "Binkies the goodbye so hard the whole meadow laughs instead of cries.", f: "A rabbit’s happy jump-and-twist is called the binky." },
    { id: "fawn", n: "Fawn", r: "The Quiet Escort", a: "Walks her to the meadow’s edge, unseen and unscented.", f: "Newborn fawns have almost no scent — invisible to noses." },
    { id: "ottie", n: "Ottie", r: "The Ferry", a: "Floats her across the river on a warm belly, favorite pebble as ballast.", f: "Otters hold hands while they sleep and keep a favorite rock." },
    { id: "echo", n: "Echo", r: "The Sonar", a: "Calls the one safe channel through the rapids.", f: "Dolphins invent names for each other — a signature whistle." },
    { id: "pounce", n: "Pounce", r: "The Retriever", a: "When the wind steals the map, pounces it back mid-air. Nailed it.", f: "Cats wiggle before pouncing to aim their back legs." },
    { id: "swan", n: "Swan", r: "The Shelter", a: "Opens one great wing over her through the storm.", f: "Swans usually pick one partner for life." },
    { id: "howl", n: "Howl", r: "The Beacon", a: "The pack sings all night so she can steer by sound in the dark.", f: "Wolves harmonize — each picks a different note so the pack sounds bigger." },
    { id: "blaze", n: "Blaze", r: "The Last Mile", a: "Runs the final valley beside her, mane streaming.", f: "Horses can sleep standing up — and lock their legs to do it." },
    { id: "pegasus", n: "Pegasus", r: "The Landing", a: "Stamps a spring where she lands — the migration’s first drink.", f: "In Greek myth, springs burst up wherever Pegasus stamped a hoof." } ] },

{ pack: "Legends Pack", accent: "#4A7A5C", ink: "#14402A", title: "The Proof",
  log: "A kid with a camera comes to the valley to prove monsters exist. The monsters hold a vote.",
  beats: [
    { t: "The Kid with the Camera", x: "Squatch — blurry as ever — spots a kid hiking in with a camera and a notebook.", c: ["squatch"] },
    { t: "The Council", x: "Nessie surfaces exactly three times to call it; Golem opens the stone hall.", c: ["nessie","golem"] },
    { t: "The Vote", x: "Cyclo and Mino vote scare, Fang votes hide, Kraken abstains dramatically. Deadlock.", c: ["cyclo","mino","fang","kraken"] },
    { t: "The Notebook", x: "Griff watches the kid rescue a fallen owlet; Phantom returns with the notebook: “I just want a friend.”", c: ["griff","phantom"] },
    { t: "The Photo", x: "They give the kid one perfect, slightly blurry group photo. Hydra’s heads agree on a pose — first time in 400 years.", c: ["hydra","squatch"] } ],
  cast: [
    { id: "squatch", n: "Squatch", r: "The Spotter", a: "Blurry as ever, first to spot the kid with the camera.", f: "“Bigfoot” got its name from 40 cm footprints found in 1958." },
    { id: "nessie", n: "Nessie", r: "The Council Call", a: "Surfaces exactly three times to summon the monster council.", f: "Loch Ness holds more water than every lake in England and Wales combined." },
    { id: "griff", n: "Griff", r: "The Witness", a: "Watches the kid rescue a fallen owlet — and changes every vote.", f: "Griffin legends may come from dinosaur skeletons found by gold miners." },
    { id: "golem", n: "Golem", r: "The Host", a: "Opens the stone hall (forehead rune set to “welcome”).", f: "In legend, a golem wakes when a single word is written on its forehead." },
    { id: "cyclo", n: "Cyclo", r: "The Scare Vote", a: "Votes to spook the kid; keeps missing with the club anyway.", f: "Cyclops myths may come from elephant skulls — the trunk hole looks like one eye." },
    { id: "fang", n: "Fang", r: "The Hide Vote", a: "Two thousand years of stories say: stay hidden.", f: "Werewolf stories are over 2,000 years old — older than most countries." },
    { id: "kraken", n: "Kraken", r: "The Abstain", a: "Abstains. Dramatically. With all the tentacles.", f: "Giant squid are real, with eyes the size of dinner plates." },
    { id: "mino", n: "Mino", r: "The Muscle Vote", a: "Cracks knuckles for the scare plan; secretly hopes it fails.", f: "The Labyrinth myth may remember a real palace with 1,300 rooms." },
    { id: "phantom", n: "Phantom", r: "The Truth", a: "Drifts back with the kid’s notebook: “I just want a friend.”", f: "“Ghost ships” on the horizon are a real mirage called fata morgana." },
    { id: "hydra", n: "Hydra", r: "The Group Photo", a: "Three heads, one pose, first agreement in 400 years — one perfect blurry photo, freely given.", f: "A real animal named the hydra regrows — cut it in half, get two hydras." } ] },

{ pack: "Turbo Pack", accent: "#E05C3A", ink: "#5A1410", title: "The Junkyard Grand Prix",
  log: "The valley’s wildest race has one rule: build it yourself.",
  beats: [
    { t: "The Poster", x: "One rule: build it yourself. Rally signs up before the ink dries.", c: ["rally"] },
    { t: "Build Week", x: "Mech welds half the grid’s rigs, Nitro mixes the fuel (supervised), Hover tunes every magnet.", c: ["mech","nitro","hover"] },
    { t: "Qualifying", x: "Turbo takes pole. Crash crashes, backflips, lands it — loudest cheer of the day.", c: ["turbo","crash"] },
    { t: "Race Day", x: "Airtime clears the gap jump; Striker bicycle-kicks a stray cone off the line at full speed.", c: ["airtime","striker"] },
    { t: "Photo Finish", x: "Champ crosses first and glove-bumps the whole grid; Titan declares everyone winners and lights the trophies off its own core.", c: ["champ","titan"] } ],
  cast: [
    { id: "rally", n: "Rally", r: "The First Entry", a: "Signs up before the poster ink dries.", f: "The fastest RC car ever hit 360 km/h." },
    { id: "turbo", n: "Turbo", r: "The Pole Sitter", a: "Takes pole position with grip that could drive on a ceiling.", f: "F1 cars grip so hard they could drive on a tunnel ceiling." },
    { id: "crash", n: "Crash", r: "The Crowd Favorite", a: "Crashes in qualifying, backflips, lands it. Loudest cheer of the day.", f: "Monster trucks can backflip. On purpose." },
    { id: "airtime", n: "Airtime", r: "The Gap Jump", a: "Clears the eight-metre gap with room to spare.", f: "The biggest BMX airs clear 8 metres — a two-storey house." },
    { id: "striker", n: "Striker", r: "The Save", a: "Bicycle-kicks a stray cone off the racing line at full speed.", f: "The fastest recorded shot flew over 200 km/h." },
    { id: "champ", n: "Champ", r: "The Sportsman", a: "First over the line — first to glove-bump every racer behind.", f: "Kangaroos can’t hop backwards — only forward, like a champ." },
    { id: "hover", n: "Hover", r: "The Tuner", a: "Tunes everyone’s magnets the night before — zero friction, all glide.", f: "Real hoverboards exist — they float on magnets." },
    { id: "nitro", n: "Nitro", r: "The Fuel", a: "Mixes race fuel (supervised) (mostly).", f: "Dragsters hit 100 km/h in under a second." },
    { id: "mech", n: "Mech", r: "The Welder", a: "Builds half the grid’s rigs in build week, one metal fist at a time.", f: "Japan built a real 18-metre robot — and it walks." },
    { id: "titan", n: "Titan", r: "The Judge", a: "Declares the whole grid winners and powers the trophy lights off its own core.", f: "The biggest land machine ever built weighs 13,500 tonnes — and it drives." } ] }

]);
