/* supabase-sync.js — cloud backup of speller profiles and progress.

   THE ONE RULE THIS FILE EXISTS TO ENFORCE
     A child's real name and their age NEVER leave the device. `shred()` below is
     the only place a child object is turned into something sendable, and it is an
     ALLOW-LIST: fields are copied in by name, so a field added to the child object
     next year is not silently uploaded. The database has no column for a name or an
     age either — two independent barriers, because one of them will eventually be
     edited by someone in a hurry.

   NOTHING RUNS UNTIL THREE THINGS ARE TRUE
     1. sb-config.js has a project URL and anon key (SB_CLOUD_ON)
     2. a parent is signed in with a confirmed email (SB_AUTH.token())
     3. that parent has given consent on the consent screen (SB_SYNC.consented())
   Any one missing and every method here is a no-op that resolves. The app must
   work on a plane; it must also work for a family that never makes an account.

   CONFLICTS ARE LAST-WRITE-WINS, PER CHILD, and that is a deliberate choice rather
   than a shrug. The alternative — merging two divergent progress blobs — invents a
   history neither device had. A child practises on one device at a time; the loser
   of a race is a few minutes of work, and the pull is only accepted when the server
   row is strictly NEWER than what this device last wrote. */
(function () {
  var SYNC_LS = 'sb_sync_v1';        // {consent_at, device, last_push, last_pull, rows:{cid:updated_at}}
  var PENDING = null, TIMER = null;

  function cfg() { return window.SB_CFG || {}; }
  function on() { try { return !!(window.SB_CLOUD_ON && window.SB_CLOUD_ON()); } catch (e) { return false; } }
  function token() { try { return window.SB_AUTH && SB_AUTH.token && SB_AUTH.token(); } catch (e) { return null; } }

  function meta() {
    try { return JSON.parse(localStorage.getItem(SYNC_LS) || 'null') || {}; } catch (e) { return {}; }
  }
  function setMeta(m) { try { localStorage.setItem(SYNC_LS, JSON.stringify(m)); } catch (e) {} }

  /* A device id, so a progress row can say which tablet wrote it last. Random, not
     derived from anything about the device or the family — it is a label for a
     conflict note, not a fingerprint, and it is regenerated by clearing site data. */
  function deviceId() {
    var m = meta();
    if (!m.device) { m.device = uuid(); setMeta(m); }
    return m.device;
  }
  function uuid() {
    try { if (crypto && crypto.randomUUID) return crypto.randomUUID(); } catch (e) {}
    var s = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx';
    return s.replace(/[xy]/g, function (c) {
      var r = (Math.random() * 16) | 0, v = c === 'x' ? r : ((r & 0x3) | 0x8);
      return v.toString(16);
    });
  }

  // ---------- REST ----------
  function rest(path, opts) {
    opts = opts || {};
    var tk = token();
    if (!on() || !tk) return Promise.reject(new Error('offline'));
    var h = {
      apikey: cfg().anon,
      Authorization: 'Bearer ' + tk,
      'Content-Type': 'application/json',
    };
    if (opts.prefer) h.Prefer = opts.prefer;
    var ctrl = (typeof AbortController !== 'undefined') ? new AbortController() : null;
    var t = ctrl ? setTimeout(function () { ctrl.abort(); }, cfg().timeoutMs || 6000) : null;
    return fetch(String(cfg().url).replace(/\/+$/, '') + '/rest/v1' + path, {
      method: opts.method || 'GET',
      headers: h,
      body: opts.body ? JSON.stringify(opts.body) : undefined,
      signal: ctrl ? ctrl.signal : undefined,
    }).then(function (r) {
      if (t) clearTimeout(t);
      return r.text().then(function (txt) {
        var j = null; try { j = txt ? JSON.parse(txt) : null; } catch (e) {}
        if (!r.ok) throw new Error((j && (j.message || j.error)) || ('HTTP ' + r.status));
        return j;
      });
    }, function (e) {
      if (t) clearTimeout(t);
      throw new Error(e && e.name === 'AbortError' ? 'slow network' : 'no connection');
    });
  }

  // ---------- what may travel ----------
  /* Copied by name. `name` and `age` are absent from BOTH lists on purpose and must
     stay that way — see the note at the top of this file. */
  var PROGRESS_KEYS = [
    'lists', 'activeList', 'vocab', 'vocabList', 'trail', 'ultra', 'trivia',
    'luMastered', 'missedWords', 'xp', 'streak', 'acc', 'week', 'goal', 'goalDone',
    'coins', 'karma', 'band', 'level', 'addons', 'tier', 'gameDiffBy', 'arcGame',
    'hive', 'evo', 'world', 'seenTips', 'ttLvSel', 'advOn', 'lastPlayed',
  ];

  /* The label a backed-up speller wears. It is derived from the AVATAR, never from
     `c.name` — the app has exactly one name field, the onboarding step asks for "first
     name or nickname", and most families type the real one. So the column called
     display_name gets "Fox", not "Ahana", and the restore screen tells them apart on
     avatar + level + date instead. A field named display_name is a standing invitation
     to put the child's name in it; this function is the answer to that invitation. */
  function label(c) {
    var a = String(c.avatar || '').replace(/[^a-z0-9]+/gi, ' ').trim();
    if (!a) return 'Speller';
    return a.charAt(0).toUpperCase() + a.slice(1, 24);
  }

  function shred(c) {
    var p = {};
    for (var i = 0; i < PROGRESS_KEYS.length; i++) {
      var k = PROGRESS_KEYS[i];
      if (c[k] !== undefined) p[k] = c[k];
    }
    return {
      row: {
        id: c.cid,
        display_name: label(c),
        spell_level: Math.max(1, Math.min(20, +(c.level || 1) || 1)),
        avatar: c.avatar || null,
        theme: c.theme || null,
      },
      payload: p,
    };
  }

  /* The reverse: a server row becomes a LOCAL child that still has no name or age,
     because the server never had them. The restore screen asks the parent for those
     two on this device — which is exactly the COPPA-shaped outcome, not a gap. */
  function rebuild(row, payload) {
    var c = { cid: row.id, avatar: row.avatar || 'bizzy', theme: row.theme || 'spellbound',
              level: row.spell_level || 1 };
    payload = payload || {};
    for (var k in payload) if (Object.prototype.hasOwnProperty.call(payload, k)) c[k] = payload[k];
    delete c.name; delete c.age;                 // belt and braces: a legacy blob cannot smuggle them back
    return c;
  }

  function children() { try { return (window.state && state.children) || []; } catch (e) { return []; } }
  function ensureIds() {
    var ch = children(), dirty = false;
    for (var i = 0; i < ch.length; i++) if (!ch[i].cid) { ch[i].cid = uuid(); dirty = true; }
    if (dirty) { try { save(); } catch (e) {} }
    return ch;
  }

  // ---------- consent ----------
  /* Consent is recorded in two places and both matter: locally, so the gate below can
     answer synchronously without a round trip, and on the account row, so it survives
     a wiped device and can be shown back to the parent as an auditable fact. */
  function consented() { return !!meta().consent_at; }

  function giveConsent() {
    var m = meta(); m.consent_at = new Date().toISOString(); setMeta(m);
    return rest('/accounts?id=eq.' + encodeURIComponent(userId()), {
      method: 'PATCH', body: { consent_at: m.consent_at, consent_device: deviceId() },
    }).catch(function () { /* recorded locally; the next push retries it */ });
  }

  function withdrawConsent() {
    var m = meta();
    delete m.consent_at; delete m.last_push; delete m.last_pull; m.rows = {};
    setMeta(m);
    return purge();
  }

  function userId() {
    try { var u = window.SB_AUTH && SB_AUTH.current(); return (u && u.id) || ''; } catch (e) { return ''; }
  }

  function ready() { return on() && !!token() && consented(); }

  // ---------- push ----------
  function push() {
    if (!ready()) return Promise.resolve({ skipped: true });
    var uid = userId(); if (!uid) return Promise.resolve({ skipped: true });
    var ch = ensureIds(); if (!ch.length) return Promise.resolve({ ok: true, n: 0 });

    var rows = [], progs = [];
    for (var i = 0; i < ch.length; i++) {
      var s = shred(ch[i]);
      s.row.parent_id = uid;
      rows.push(s.row);
      progs.push({ child_id: s.row.id, parent_id: uid, payload: s.payload, device_id: deviceId() });
    }
    /* One upsert for the profiles, one for the progress. merge-duplicates is what makes
       a re-push idempotent — the same child pushed twice updates rather than colliding. */
    return rest('/children?on_conflict=id', { method: 'POST', body: rows, prefer: 'resolution=merge-duplicates,return=minimal' })
      .then(function () {
        return rest('/progress?on_conflict=child_id', { method: 'POST', body: progs, prefer: 'resolution=merge-duplicates,return=minimal' });
      })
      .then(function () {
        var m = meta(); m.last_push = Date.now(); m.err = null; setMeta(m);
        return { ok: true, n: rows.length };
      })
      .catch(function (e) {
        var m = meta(); m.err = e.message; setMeta(m);
        return { error: e.message };
      });
  }

  /* Called from save(). Coalesced, because save() fires on nearly every interaction and
     a request per keystroke would be both rude and slow. */
  function queue() {
    if (!ready()) return;
    PENDING = true;
    if (TIMER) return;
    TIMER = setTimeout(function () { TIMER = null; if (PENDING) { PENDING = false; push(); } }, 4000);
  }

  // ---------- pull ----------
  /* Returns the server's spellers WITHOUT touching local state. Deciding what to do
     with them is the restore screen's job, not this file's — silently overwriting a
     child's device because another tablet was newer is how you lose an afternoon of
     work to a bug in a merge rule. */
  function fetchAll() {
    if (!on() || !token()) return Promise.resolve({ error: 'offline' });
    return rest('/children?select=id,display_name,spell_level,avatar,theme,updated_at&order=updated_at.desc')
      .then(function (kids) {
        kids = kids || [];
        if (!kids.length) return { kids: [] };
        return rest('/progress?select=child_id,payload,updated_at,device_id').then(function (ps) {
          var by = {}; (ps || []).forEach(function (p) { by[p.child_id] = p; });
          var m = meta(); m.last_pull = Date.now(); setMeta(m);
          return { kids: kids.map(function (k) {
            var p = by[k.id] || {};
            return { row: k, payload: p.payload || {}, updated_at: p.updated_at || k.updated_at,
                     device: p.device_id || null, child: rebuild(k, p.payload) };
          }) };
        });
      })
      .catch(function (e) { return { error: e.message }; });
  }

  // ---------- deletion ----------
  function delChild(cid) {
    if (!ready() || !cid) return Promise.resolve({ skipped: true });
    return rest('/children?id=eq.' + encodeURIComponent(cid), { method: 'DELETE', prefer: 'return=minimal' })
      .then(function () { return { ok: true }; })
      .catch(function (e) { return { error: e.message }; });
  }

  /* Withdrawing consent has to actually delete, not merely stop uploading — that is
     the promise the consent screen and the privacy policy both make. Progress rows
     cascade from children, so one delete is enough. */
  function purge() {
    if (!on() || !token()) return Promise.resolve({ skipped: true });
    var uid = userId(); if (!uid) return Promise.resolve({ skipped: true });
    return rest('/children?parent_id=eq.' + encodeURIComponent(uid), { method: 'DELETE', prefer: 'return=minimal' })
      .then(function () {
        return rest('/accounts?id=eq.' + encodeURIComponent(uid), {
          method: 'PATCH', body: { consent_at: null, consent_device: null },
        }).catch(function () {});
      })
      .then(function () { return { ok: true }; })
      .catch(function (e) { return { error: e.message }; });
  }

  function status() {
    var m = meta();
    return {
      configured: on(),
      signedIn: !!token(),
      consented: consented(),
      active: ready(),
      lastPush: m.last_push || 0,
      lastPull: m.last_pull || 0,
      device: m.device || null,
      error: m.err || null,
    };
  }

  window.SB_SYNC = {
    status: status, ready: ready, consented: consented,
    giveConsent: giveConsent, withdrawConsent: withdrawConsent,
    push: push, queue: queue, fetchAll: fetchAll,
    delChild: delChild, purge: purge,
    ensureIds: ensureIds, shred: shred, rebuild: rebuild, label: label,
    PROGRESS_KEYS: PROGRESS_KEYS,
  };
})();
