/* Bizzing Bee — Theme Journeys: 50 themes in 8 clusters.
   Each theme carries a classifier: `re` is matched against a word's DEFINITION (case-insensitive),
   `ore` (optional) against its origin, `wre` (optional) against the word itself. A word joins a
   theme if the definition matches — so themes assemble themselves from the 17k-word database. */
window.SB_THEMES = {
clusters:[
 { id:'science',  label:'Science & Nature',   c:'#13A892', c2:'#0E8A78', tex:'rings'  },
 { id:'earth',    label:'Earth & Place',      c:'#4F9E6A', c2:'#3C8455', tex:'stripes'},
 { id:'living',   label:'Food & Living',      c:'#E0922E', c2:'#C8791B', tex:'diag'   },
 { id:'arts',     label:'Arts & Culture',     c:'#B14FC4', c2:'#9438A8', tex:'dots'   },
 { id:'society',  label:'People & Society',   c:'#3D7DF0', c2:'#2A63D6', tex:'grid'   },
 { id:'history',  label:'History & Conflict', c:'#C24545', c2:'#A33232', tex:'cross'  },
 { id:'play',     label:'Movement & Play',    c:'#FF5FA2', c2:'#E8458C', tex:'dots'   },
 { id:'mind',     label:'Language & Mind',    c:'#7B52E0', c2:'#5E39C4', tex:'stripes'},
 { id:'origins',  label:'Where Words Come From', c:'#C08A3E', c2:'#8A5B00', tex:'diag'  },
 { id:'named',    label:'Named After Someone', c:'#E8458C', c2:'#A82563', tex:'dots'   },
],
themes:[
 // ---- Science & nature ----
 { id:'body',     cluster:'science', hero:'anatomy',   label:'Human Body & Medicine',  sub:'Anatomy, organs, doctors & healing', re:'\\b(anatom|artery|arteries|bone|muscle|nerve|organ of|gland|tissue|skull|spine|vertebra|abdomen|lung|liver|kidney|heart\\b|blood|vein|skin\\b|medic|surg|physician|hospital|clinic|therap|diagnos|anesthe|dental|tooth|teeth|stomach|intestin|brain|cranial|larynx|pharynx|femur|tendon|ligament|cartilage|joint of|limb|torso|scalp|follicle)' },
 { id:'disease',  cluster:'science', hero:'malady',    label:'Diseases & Symptoms',    sub:'Ailments, infections & what they feel like', re:'\\b(disease|illness|infection|inflammat|fever|symptom|disorder|syndrome|ailment|epidemic|pandemic|contagio|virus|bacteri|tumor|cancer|allerg|rash\\b|swelling|paralysis|nausea|vertigo|chronic|acute (pain|illness)|pathogen|malady|affliction|lesion|abscess|dementia|diabetes|asthma)' },
 { id:'pharmacy', cluster:'science', hero:'remedy',    label:'Drugs & Pharmacy',       sub:'Medicines, remedies & potions', re:'\\b(drug|medicin|remedy|remedies|antidote|dose|dosage|pharmac|pill\\b|tablet|ointment|salve|tonic|vaccine|antibiotic|sedative|narcotic|potion|elixir|serum|penicillin|aspirin|prescription)' },
 { id:'animals',  cluster:'science', hero:'creature',  label:'Animals & Zoology',      sub:'Mammals, reptiles & the animal kingdom', re:'\\b(mammal|animal|beast|carnivor|herbivor|rodent|primate|feline|canine\\b|reptile|amphibian|lizard|snake|frog|toad|monkey|ape\\b|bear\\b|wolf|wolves|fox\\b|deer\\b|antelope|elephant|rhinoceros|hippopotamus|giraffe|zebra|camel|llama|sheep|goat\\b|cattle|horse|pony|donkey|pig\\b|swine|marsupial|kangaroo|possum|bat\\b|hedgehog|badger|otter|weasel|zoolog)' },
 { id:'birds',    cluster:'science', hero:'plumage',   label:'Birds',                  sub:'From sparrows to seabirds', re:'\\b(bird|fowl|hawk|eagle|falcon|owl\\b|owls\\b|parrot|sparrow|finch|thrush|warbler|heron|crane\\b|stork|pelican|gull|tern\\b|duck\\b|goose|geese|swan|pigeon|dove\\b|crow\\b|raven|magpie|woodpecker|hummingbird|ostrich|penguin|plumage|beak|feather|nest of|ornitholog|aviary)' },
 { id:'insects',  cluster:'science', hero:'chrysalis', label:'Insects & Bugs',         sub:'Beetles, butterflies & creepy-crawlies', re:'\\b(insect|beetle|butterfly|butterflies|moth\\b|moths\\b|caterpillar|larva|pupa|chrysalis|cocoon|bee\\b|bees\\b|wasp|hornet|ant\\b|ants\\b|termite|cricket|grasshopper|locust|cicada|dragonfly|mosquito|flea|gnat|aphid|spider|arachnid|scorpion|centipede|millipede|entomolog)' },
 { id:'marine',   cluster:'science', hero:'abyssal',   label:'Marine Life',            sub:'Fish, whales & creatures of the deep', re:'\\b(fish\\b|fishes|shark|whale|dolphin|porpoise|seal\\b|walrus|octopus|squid|jellyfish|crab\\b|lobster|shrimp|oyster|clam\\b|mussel|barnacle|coral|plankton|eel\\b|salmon|trout|herring|cod\\b|tuna|marine (animal|life|mammal)|aquatic|mollusk|crustacean)' },
 { id:'botany',   cluster:'science', hero:'flora',     label:'Plants & Botany',        sub:'How plants grow, bloom & seed', re:'\\b(plant\\b|plants\\b|botan|leaf|leaves|stem\\b|root\\b|roots\\b|seed\\b|seeds\\b|pollen|photosynthe|sap\\b|bud\\b|sprout|germinat|fungus|fungi|moss\\b|fern\\b|algae|lichen|vine\\b|shrub|herb\\b|grass\\b|grasses|weed\\b|flora\\b)' },
 { id:'flowers',  cluster:'science', hero:'blossom',   label:'Trees & Flowers',        sub:'Blossoms, orchards & mighty oaks', re:'\\b(tree\\b|trees\\b|flower|blossom|bloom|petal|orchid|rose\\b|roses\\b|lily|lilies|tulip|daisy|daisies|violet\\b|jasmine|lotus|oak\\b|pine\\b|maple|birch|cedar|willow|palm tree|cypress|eucalyptus|magnolia|bamboo|orchard|grove|arboret)' },
 { id:'chemistry',cluster:'science', hero:'catalyst',  label:'Chemistry & Elements',   sub:'Atoms, acids & reactions', re:'\\b(chemi|element\\b|compound\\b|molecule|atom\\b|atoms\\b|atomic|acid\\b|acids\\b|alkali|oxide|oxygen|hydrogen|nitrogen|carbon\\b|sulfur|sodium|potassium|calcium\\b|iron\\b|copper|zinc|mercury\\b|lead\\b(?!er)|alloy|catalyst|solvent|solution of|crystall|distill|ferment|corrode|combust)' },
 { id:'astronomy',cluster:'science', hero:'nebula',    label:'Astronomy & Space',      sub:'Stars, planets & the night sky', re:'\\b(star\\b|stars\\b|stellar|planet|orbit|moon\\b|lunar|solar|sun\\b|comet|meteor|asteroid|galaxy|galaxies|nebula|cosmos|cosmic|universe|telescope|astronom|constellation|eclipse|equinox|solstice|zodiac|celestial|satellite|astronaut)' },
 { id:'weather',  cluster:'science', hero:'tempest',   label:'Weather & Climate',      sub:'Storms, seasons & sky-signs', re:'\\b(weather|climate|storm|rain\\b|rains\\b|rainfall|snow\\b|snowfall|hail\\b|sleet|frost|fog\\b|mist\\b|cloud|wind\\b|winds\\b|breeze|gale\\b|hurricane|tornado|cyclone|typhoon|monsoon|drought|thunder|lightning|humidity|barometer|meteorolog|blizzard|tempest)' },
 { id:'minerals', cluster:'science', hero:'geode',     label:'Rocks, Minerals & Gems', sub:'Crystals, ores & precious stones', re:'\\b(rock\\b|rocks\\b|stone\\b|stones\\b|mineral|crystal|gem\\b|gems\\b|gemstone|quartz|granite|marble\\b|limestone|slate\\b|ore\\b|ores\\b|diamond|ruby|rubies|emerald|sapphire|pearl|opal|jade\\b|amber\\b|obsidian|basalt|sediment|igneous|geolog|fossil)' },
 { id:'physics',  cluster:'science', hero:'momentum',  label:'Physics & Forces',       sub:'Energy, motion & machines of nature', re:'\\b(physics|force\\b|forces\\b|energy|gravit|momentum|velocity|accelerat|friction|magnet|electric|electron|proton|neutron|particle|radiation|radioactiv|frequency|wavelength|optic|lens\\b|prism|inertia|pendulum|thermodynam|quantum)' },
 { id:'ecology',  cluster:'science', hero:'habitat',   label:'Ecology & Habitats',     sub:'Ecosystems & where life lives', re:'\\b(ecolog|ecosystem|habitat|environment|wildlife|conservation|endangered|extinct|biodiversity|food chain|predator|prey\\b|nocturnal|hibernat|migrat|camouflage|wetland|rainforest|savanna|tundra|biome)' },
 // ---- Earth & place ----
 { id:'landforms',cluster:'earth',   hero:'nunatak',   label:'Geographical Features',  sub:'Peaks, valleys & strange landforms', re:'\\b(mountain|hill\\b|hills\\b|valley|plateau|plain\\b|plains\\b|cliff|canyon|gorge|ravine|cave\\b|cavern|glacier|volcano|crater|peninsula|island|isthmus|delta\\b|dune\\b|dunes\\b|mesa\\b|fjord|lagoon|marsh|swamp|bog\\b|oasis|desert\\b|tundra|steppe|landform|terrain|topograph)' },
 { id:'nations',  cluster:'earth',   hero:'demonym',   label:'Nations & Peoples',      sub:'Countries, cities & their peoples', re:'\\b(native or inhabitant|inhabitant of|citizen of|a person from|people of (a|the)|country in|capital (city|of)|nation\\b|nationality|demonym)' },
 { id:'waterways',cluster:'earth',   hero:'estuary',   label:'Rivers, Seas & Oceans',  sub:'Currents, tides & flowing water', re:'\\b(river|stream\\b|streams\\b|brook\\b|creek|sea\\b|seas\\b|ocean|tide|tidal|current of water|waterfall|rapids|estuary|strait|gulf\\b|bay\\b|bays\\b|harbor|shore|coast|beach|waves\\b|flood|irrigat|channel of water|tributary)' },
 { id:'maps',     cluster:'earth',   hero:'meridian',  label:'Maps & Navigation',      sub:'Finding your way across the world', re:'\\b(map\\b|maps\\b|navigat|compass|latitude|longitude|meridian|equator|hemisphere|cartograph|atlas|globe\\b|boundary|border of|route\\b|bearing|due (north|south|east|west)|coordinates|surveying|landmark)' },
 { id:'farming',  cluster:'earth',   hero:'harvest',   label:'Agriculture & Farming',  sub:'Fields, crops & the harvest', re:'\\b(farm|agricultur|crop\\b|crops\\b|harvest|plow|plough|sow\\b|sowing|cultivat|orchard|vineyard|pasture|meadow|barn\\b|silo|granary|livestock|dairy|shepherd|graze|grazing|fertilizer|scythe|hay\\b|wheat|barley|rye\\b|oats\\b)' },
 // ---- Food & living ----
 { id:'culinary', cluster:'living',  hero:'sauté',     label:'Culinary Arts',          sub:'Cooking methods & the kitchen', re:'\\b(cook|bake|baking|roast|boil|simmer|fry|fried|grill|saute|sauté|knead|whisk|marinat|season(ed|ing)|recipe|kitchen|chef|cuisine|culinary|broth|stew\\b|sauce|batter|dough|garnish|appetizer|entree|dessert)' },
 { id:'dishes',   cluster:'living',  hero:'knaidel',   label:'World Dishes',           sub:'Foods & dishes from everywhere', re:'\\b(a dish of|dish made|food made|bread\\b|breads\\b|cake\\b|cakes\\b|pastry|pastries|soup\\b|soups\\b|dumpling|noodle|pasta|cheese|sausage|pie\\b|pies\\b|pudding|porridge|pancake|tortilla|curry|sushi|pizza|salad|sandwich|casserole|omelet|croissant|beverage|drink made)' },
 { id:'spices',   cluster:'living',  hero:'saffron',   label:'Fruits, Veg & Spices',   sub:'From orchards & spice routes', re:'\\b(fruit|fruits|berry|berries|apple|orange\\b|banana|mango|peach|pear\\b|plum\\b|grape|melon|cherry|cherries|vegetable|potato|tomato|onion|garlic|carrot|cabbage|lettuce|spinach|pepper\\b|bean\\b|beans\\b|pea\\b|peas\\b|spice|cinnamon|ginger|saffron|vanilla|clove|nutmeg|cumin|turmeric|basil|mint\\b|herb used)' },
 { id:'fabrics',  cluster:'living',  hero:'marocain',  label:'Fabrics & Fashion',      sub:'Cloth, garments & style', re:'\\b(fabric|cloth\\b|cloths|textile|silk|cotton|wool|linen|velvet|satin|lace\\b|garment|dress\\b|dresses|gown|coat\\b|cloak|jacket|trousers|skirt|hat\\b|hats\\b|bonnet|scarf|shawl|veil\\b|glove|boot\\b|shoe|sandal|embroider|weave|woven|tailor|seamstress|fashion|attire|apparel|costume)' },
 { id:'buildings',cluster:'living',  hero:'transept',  label:'Architecture',           sub:'Buildings & how they’re made', re:'\\b(architect|building|column|pillar|arch\\b|arches|dome\\b|vault|spire|steeple|tower|facade|balcony|courtyard|corridor|chamber|attic|cellar|basement|foundation of|scaffold|mansion|palace|castle|cathedral|chapel|temple\\b|monastery|fortress|masonry|brick|mortar\\b|rafter|gable|transept|nave\\b)' },
 { id:'household',cluster:'living',  hero:'armoire',   label:'Home & Objects',         sub:'Furniture & everyday things', re:'\\b(furniture|chair|table\\b|tables\\b|desk\\b|bed\\b|beds\\b|sofa|couch|cupboard|cabinet|drawer|shelf|shelves|wardrobe|mirror|lamp\\b|candle|curtain|carpet|rug\\b|blanket|pillow|cushion|utensil|kettle|teapot|jug\\b|vase|basket|bucket|broom|household)' },
 // ---- Arts & culture ----
 { id:'music',    cluster:'arts',    hero:'sonata',    label:'Music & Instruments',    sub:'Notes, rhythms & the orchestra', re:'\\b(music|melody|melodies|harmony|harmonies|rhythm|tempo|song\\b|songs\\b|singing|singer|choir|chorus|orchestra|symphony|sonata|concerto|opera\\b|instrument|piano|violin|cello|flute|clarinet|oboe|trumpet|trombone|drum\\b|drums\\b|guitar|harp\\b|organ\\b|note in music|musical|composer|conductor|soprano|tenor\\b|baritone)' },
 { id:'stage',    cluster:'arts',    hero:'soubrette', label:'Dance & Theater',        sub:'The stage, the steps, the spotlight', re:'\\b(dance|ballet|waltz|tango|polka|choreograph|theater|theatre|stage\\b|drama|play\\b(?! on)|actor|actress|comedy|comedian|tragedy|pantomime|puppet|rehears|audition|curtain call|matinee|troupe|vaudeville|mime\\b)' },
 { id:'painting', cluster:'arts',    hero:'fresco',    label:'Painting & Sculpture',   sub:'Canvas, chisel & color', re:'\\b(paint|painting|painter|canvas|portrait|landscape painting|mural|fresco|sketch|drawing|sculpt|statue|carving|engrav|etching|mosaic|palette|pigment|easel|gallery|museum|masterpiece|artistic|artwork|watercolor)' },
 { id:'poetry',   cluster:'arts',    hero:'sonnet',    label:'Literature & Poetry',    sub:'Stories, verses & how they’re built', re:'\\b(poem|poetry|poet\\b|poets\\b|verse|stanza|rhyme|meter in poetry|sonnet|ballad|epic\\b|novel\\b|novels\\b|story|stories|narrative|fable|tale\\b|tales\\b|literature|literary|author|writer|chapter|manuscript|prose|metaphor|simile|allegory|satire|essay)' },
 { id:'myth',     cluster:'arts',    hero:'olympian',  label:'Mythology',              sub:'Gods, heroes & monsters of legend', re:'\\b(myth|legend|god of|goddess|deity|deities|zeus|apollo|athena|hercules|odysseus|titan|nymph|muse\\b|muses\\b|centaur|minotaur|phoenix|dragon|unicorn|griffin|mermaid|giant of|underworld|olymp|norse god|folklore hero|oracle)' },
 { id:'religion', cluster:'arts',    hero:'koinonia',  label:'Religions & Rituals',    sub:'Faiths, festivals & sacred things', re:'\\b(religio|sacred|holy|worship|prayer|temple|church|mosque|synagogue|shrine|altar|priest|monk\\b|monks\\b|nun\\b|nuns\\b|rabbi|imam|pilgrim|ritual|ceremony|blessing|scripture|bible|torah|koran|quran|hymn|psalm|sabbath|passover|ramadan|baptism|meditation|spiritual)' },
 { id:'festivals',cluster:'arts',    hero:'carnival',  label:'Folklore & Festivals',   sub:'Celebrations & old traditions', re:'\\b(festival|carnival|celebration|holiday|parade|feast\\b|feasts\\b|folklore|folk (tale|song|dance)|tradition|custom of|superstition|charm against|amulet|talisman|masquerade|fireworks|bonfire|jubilee)' },
 // ---- People & society ----
 { id:'law',      cluster:'society', hero:'verdict',   label:'Law & Justice',          sub:'Courts, judges & the rules', re:'\\b(law\\b|laws\\b|legal|court\\b|courts\\b|judge|jury|juror|trial|verdict|testimony|witness|attorney|lawyer|plaintiff|defendant|accus|guilt|innocen|sentence(d)? to|prison|jail|crime|criminal|theft|felony|contract|statute|decree|edict|subpoena|acquit|indict)' },
 { id:'politics', cluster:'society', hero:'demarche',  label:'Government & Politics',  sub:'Leaders, laws & how nations run', re:'\\b(government|governor|politic|democracy|democratic|republic|monarch|president|parliament|congress|senate|senator|election|vote|voting|ballot|campaign|candidate|ambassador|diplomat|treaty|policy|policies|citizen|bureaucra|legislat|constitution|mayor|council)' },
 { id:'economy',  cluster:'society', hero:'cambist',   label:'Money & Trade',          sub:'Markets, merchants & coins', re:'\\b(money|currency|currencies|coin\\b|coins\\b|dollar|bank\\b|banks\\b|banking|merchant|trade\\b|trading|commerce|commercial|market|bargain|profit|debt\\b|debts\\b|loan\\b|tax\\b|taxes|wealth|treasur|economy|economic|auction|invoice|ledger|salary|wages|invest|barter|tariff)' },
 { id:'jobs',     cluster:'society', hero:'artisan',   label:'Occupations & Trades',   sub:'Crafts & the people who work them', re:'\\b(person who (makes|sells|works|repairs|studies)|one who (makes|sells|works|studies)|occupation|profession\\b|craftsman|artisan|apprentice|blacksmith|carpenter|cobbler|mason\\b|miller|tanner|cooper\\b|clerk|barber|butcher|baker\\b|florist|jeweler|locksmith|plumber)' },
 { id:'character',cluster:'society', hero:'insouciant',label:'Personality & Character',sub:'Words that describe people', re:'\\b(person who is|someone who is|characterized by|tending to|inclined to|disposition|temperament|(being|is) (cheerful|gloomy|stubborn|shy|bold|proud|humble|honest|lazy|brave|timid|careless|carefree|indifferent)|good-natured|bad-tempered|easily (angered|annoyed)|quick-tempered)' },
 { id:'emotions', cluster:'society', hero:'euphoria',  label:'Emotions & Moods',       sub:'Joys, fears & feelings', re:'\\b(emotion|feeling of|mood\\b|moods\\b|joy\\b|joyful|happiness|sorrow|sadness|grief|anger|angry|rage\\b|fear\\b|fears\\b|dread|anxiety|anxious|delight|despair|hope\\b|longing|jealousy|envy\\b|pity|sympathy|affection|melanchol|euphori|nostalgi|ecstasy|gloom)' },
 { id:'kinship',  cluster:'society', hero:'sibling',   label:'Family & Kinship',       sub:'Relatives & relationships', re:'\\b(family|families|mother|father|parent|child\\b|children|son\\b|sons\\b|daughter|brother|sister|sibling|uncle|aunt\\b|cousin|nephew|niece|grandmother|grandfather|ancestor|descendant|heir\\b|heirs\\b|kin\\b|kinship|marriage|wedding|bride|groom|widow|orphan|household of)' },
 // ---- History & conflict ----
 { id:'war',      cluster:'history', hero:'garrison',  label:'War & Weaponry',         sub:'Battles, armor & strategy', re:'\\b(war\\b|wars\\b|warfare|battle|soldier|army|armies|navy|naval|troop|regiment|garrison|fortress|siege|weapon|sword|dagger|spear|lance\\b|arrow|bow and|shield|armor|cannon|musket|rifle|pistol|bullet|grenade|ambush|invasion|conquer|combat|military|cavalry|infantry|admiral|general of)' },
 { id:'ancient',  cluster:'history', hero:'pharaoh',   label:'Ancient Civilizations',  sub:'Pyramids, ruins & lost empires', re:'\\b(ancient|antiquity|pharaoh|pyramid|mummy|mummies|hieroglyph|sarcophagus|rome\\b|roman|greece|greek city|sparta|athens|gladiator|colosseum|aqueduct|toga\\b|empire of|babylon|mesopotam|aztec|maya\\b|mayan|inca\\b|archaeolog|ruins|artifact|relic)' },
 { id:'royalty',  cluster:'history', hero:'regalia',   label:'Royalty & Heraldry',     sub:'Crowns, courts & coats of arms', re:'\\b(king\\b|kings\\b|queen|prince|princess|royal|royalty|throne|crown|monarch|emperor|empress|duke\\b|duchess|earl\\b|baron|count(ess)? of|knight|nobility|noble\\b|nobles\\b|courtier|palace|scepter|regal|coronation|heraldry|coat of arms|dynasty|majesty)' },
 { id:'seafaring',cluster:'history', hero:'catamaran', label:'Exploration & Seafaring',sub:'Ships, voyages & discovery', re:'\\b(ship\\b|ships\\b|boat\\b|boats\\b|sail|sailor|voyage|expedition|explorer|navigate the sea|mariner|nautical|maritime|vessel|deck of|mast\\b|anchor|rudder|harbor|port\\b|wharf|dock\\b|canoe|kayak|raft\\b|ferry|galleon|schooner|frigate|compass rose|crew of)' },
 // ---- Movement & play ----
 { id:'sports',   cluster:'play',    hero:'abseil',    label:'Sports & Games',         sub:'Contests, courts & champions', re:'\\b(sport|game\\b|games\\b|athlete|athletic|race\\b|races\\b|racing|competition|tournament|match\\b|team\\b|teams\\b|player|goal\\b|score|wrestling|boxing|gymnast|swimming|diving|skiing|skating|tennis|golf\\b|soccer|football|baseball|basketball|hockey|archery|fencing|marathon|olympic|referee|umpire|chess)' },
 { id:'vehicles', cluster:'play',    hero:'velocipede',label:'Vehicles & Transport',   sub:'Wheels, wings & ways to travel', re:'\\b(vehicle|carriage|wagon|cart\\b|carts\\b|chariot|coach\\b|automobile|car\\b|cars\\b|truck|bus\\b|train\\b|trains\\b|railway|railroad|locomotive|bicycle|tricycle|motorcycle|airplane|aircraft|helicopter|glider|balloon flight|rocket|sled\\b|sleigh|tram\\b|subway|taxi)' },
 { id:'tools',    cluster:'play',    hero:'stromuhr',  label:'Tools & Machines',       sub:'Gadgets, gears & instruments', re:'\\b(tool\\b|tools\\b|machine|instrument for|device|apparatus|gadget|mechanism|engine|motor\\b|gear\\b|gears\\b|lever|pulley|hammer|saw\\b|saws\\b|drill|chisel|wrench|screwdriver|axe\\b|shovel|clock\\b|watch(es)? for telling|gauge|meter for|microscope|thermometer|telescope for)' },
 // ---- Language & mind ----
 { id:'logic',    cluster:'mind',    hero:'paradox',   label:'Logic & Philosophy',     sub:'Big ideas & how we reason', re:'\\b(philosoph|logic|logical|reason(ing)?\\b|argument|theory|theories|hypothesis|premise|conclusion|paradox|ethic|moral\\b|morals\\b|morality|virtue|wisdom|knowledge|truth\\b|belief|doctrine|principle|rational|skeptic|stoic\\b|metaphys|epistem|dialectic)' },
 { id:'numbers',  cluster:'mind',    hero:'quotient',  label:'Math & Measurement',     sub:'Numbers, shapes & sizes', re:'\\b(number|mathemat|arithmetic|geometry|algebra|calculus|equation|fraction|decimal|percent|multiply|multiplication|divide|division|subtract|addition|sum of|angle|triangle|circle\\b|square\\b|polygon|diameter|radius|circumference|measure|measurement|unit of|weight of|length of|quotient|integer|numeral)' },
 /* The championship shelf: the words the core library never held — long,
    obscure and foreign-origin, gathered field by field. They carry the
    'championship' tag, and a word joins a theme when the theme's id is in
    its tags, so this needs no `re` classifier at all. */
 { id:'championship',cluster:'mind', hero:'psammophile', label:'The Championship Words',  sub:'The hardest words in the hive — long, rare and foreign-born' },
 { id:'wordwords',cluster:'mind',    hero:'euonym',    label:'Words about Words',      sub:'Language, letters & linguistics', re:'\\b(word\\b|words\\b|language|linguistic|grammar|grammat|vocabulary|dialect|accent\\b|pronunciation|pronounce|alphabet|letter of the|syllable|vowel|consonant|noun\\b|verb\\b|adjective|adverb|prefix|suffix|etymolog|synonym|antonym|idiom|phrase|sentence structure|spelling|dictionary|translat)' },
 { id:'time',     cluster:'mind',    hero:'ephemeral', label:'Time & Seasons',         sub:'Moments, ages & the calendar', re:'\\b(time\\b|times\\b|hour|minute\\b|moment|day\\b|days\\b|daily|week\\b|weekly|month|year\\b|years\\b|yearly|annual|century|centuries|decade|era\\b|eras\\b|epoch|season|spring\\b|summer|autumn|winter|dawn\\b|dusk\\b|twilight|midnight|noon\\b|calendar|clock|ancient times|eternal|everlasting|temporary|fleeting|ephemeral)' },
 { id:'colors',   cluster:'mind',    hero:'cerulean',  label:'Colors & Light',         sub:'Hues, shades & shimmer', re:'\\b(color|colour|hue\\b|hues\\b|shade of|tint|crimson|scarlet|vermilion|azure|cerulean|indigo|violet color|turquoise|emerald green|golden|silver(y)?\\b|ebony|ivory|iridescent|luminous|radiant|gleam|glow\\b|glowing|shimmer|sparkle|dazzle|brilliance|light and|prismatic|opalescent)' },
 { id:'eponyms',  cluster:'mind',    hero:'sideburns', label:'Named After Someone',    sub:'Words born from real names', re:'\\b(named (after|for|in honou?r of)|takes its name from|derives its name from|coined (after|from the name)|from the name of)\\b' },

 // ---- Where words come from (origin families, straight from the book series) ----
 // These classify on a word's ORIGIN, not its meaning, so they cut the library the
 // way the Word Atlas and the books do. `ore` is the origin matcher.
 { id:'olatin',   cluster:'origins', hero:'forum',     label:'Latin — Rome\u2019s Long Reach', sub:'The single biggest layer in English', ore:'latin' },
 { id:'ogreek',   cluster:'origins', hero:'elements',  label:'Greek — The Science Language', sub:'PH, CH, PS, RH and the silent openers', ore:'greek' },
 { id:'ofrench',  cluster:'origins', hero:'strait',    label:'French — The Norman Layer', sub:'Endings that look nothing like they sound', ore:'french|anglo-norman' },
 { id:'oiberian', cluster:'origins', hero:'strait',    label:'Italian, Spanish & Portuguese', sub:'Opera, ocean and open vowels', ore:'italian|spanish|portuguese|catalan|galician' },
 { id:'onordic',  cluster:'origins', hero:'greysea',   label:'German & Nordic Cousins', sub:'Compounds, hard consonants, blunt spellings', ore:'german|norse|danish|swedish|norwegian|icelandic|scandinavian|finnish|yiddish' },
 { id:'odutch',   cluster:'origins', hero:'strait',    label:'Dutch — The Sailors\u2019 Loan', sub:'The largest origin nobody teaches', ore:'dutch|afrikaans|flemish' },
 { id:'oceltic',  cluster:'origins', hero:'meadow',    label:'Celtic — Irish, Welsh, Scots & Gaelic', sub:'Consonant clusters English never invented', ore:'irish|welsh|scots|gaelic|celtic|cornish|breton|manx' },
 { id:'osouth',   cluster:'origins', hero:'grandtrunk',label:'South Asian — Sanskrit to Persian', sub:'The aspirated letters: bh, dh, gh, kh, th', ore:'sanskrit|hindi|urdu|tamil|bengali|marathi|telugu|malayalam|kannada|gujarati|punjabi|sinhala|nepali|pali|prakrit' },
 { id:'oeastasia',cluster:'origins', hero:'origami',   label:'Japanese, Chinese & Korean', sub:'Words that arrive already spelled', ore:'japanese|chinese|mandarin|cantonese|yue|korean' },
 { id:'osemitic', cluster:'origins', hero:'junkyard',  label:'Arabic & Hebrew — The Desert Roads', sub:'AL- words and the letters that came with them', ore:'arabic|hebrew|aramaic|syriac|phoenician' },
 { id:'oslavic',  cluster:'origins', hero:'warfield',  label:'Russian & Slavic', sub:'Suffixes that name things', ore:'russian|polish|czech|slovak|serbian|croatian|bulgarian|ukrainian|slavic|slavonic' },
 { id:'oturkic',  cluster:'origins', hero:'engine',    label:'Persian & Turkish — The Silk Road', sub:'Words that walked a very long way', ore:'persian|turkish|turkic|tatar|mongol|uzbek|azerbaijani' },
 { id:'opacific', cluster:'origins', hero:'strait',    label:'Malay, Maori & Hawaiian', sub:'Open syllables, doubled vowels', ore:'malay|indonesian|javanese|tagalog|maori|hawaiian|samoan|tongan|polynesian|melanesian|fijian' },
 { id:'oworld',   cluster:'origins', hero:'meadow',    label:'The Americas & Africa', sub:'Nahuatl, Quechua, Bantu, Yoruba, Swahili', ore:'nahuatl|quechua|algonquian|powhatan|narragansett|ojibwa|cree|inuit|aleut|carib|taino|tupi|guarani|mayan|american indian|native american|bantu|yoruba|swahili|zulu|xhosa|wolof|akan|twi|igbo|hausa|mandingo|kongo|african' },
 { id:'ooldeng',  cluster:'origins', hero:'meadow',    label:'Old English — The Home Layer', sub:'The oldest words we own, and their odd spellings', ore:'old english|anglo-saxon|middle english' },

 // ---- Named after someone (eponyms, clustered by the donor language of the NAME) ----
 // Same clustering the Champion Ladder uses: a Greek hero\u2019s name and a French
 // inventor\u2019s name break in completely different places.
 { id:'epgreek',  cluster:'named', hero:'elements',  label:'Eponyms I — Greek Myth & Names', sub:'Gods, heroes and the words they left behind', tag:'eponyms', ore:'greek' },
 { id:'eplatin',  cluster:'named', hero:'forum',     label:'Eponyms II — Latin & Roman Names', sub:'Emperors, generals, and Roman households', tag:'eponyms', ore:'latin' },
 { id:'epfrench', cluster:'named', hero:'stage',     label:'Eponyms III — French Names', sub:'Inventors, chefs and aristocrats', tag:'eponyms', ore:'french|anglo-norman' },
 { id:'epiber',   cluster:'named', hero:'strait',    label:'Eponyms IV — Italian & Spanish Names', sub:'Scientists, sailors and saints', tag:'eponyms', ore:'italian|spanish|portuguese' },
 { id:'epnordic', cluster:'named', hero:'greysea',   label:'Eponyms V — German & Nordic Names', sub:'Physicists, botanists and unit names', tag:'eponyms', ore:'german|dutch|norse|danish|swedish|norwegian|finnish' },
 { id:'epeng',    cluster:'named', hero:'library',   label:'Eponyms VI — English & Celtic Names', sub:'Earls, engineers and eccentrics', tag:'eponyms', ore:'english|scots|irish|welsh' },
 { id:'epworld',  cluster:'named', hero:'grandtrunk',label:'Eponyms VII — Names from Everywhere Else', sub:'The rest of the world\u2019s namesakes', tag:'eponyms' },
]};
