/* Bizzing Bee — parent coaching tips library (fully offline; picked by analytics rules, never AI).
   Categories are matched to signals in parentTips(); the engine also composes tips from the
   121 concepts, 52 themes, word origins and the child's own missed words — 1,000+ distinct tips. */
window.SB_TIPS = {
reengage:[
"Shrink the ask: after a break, restart with just 5 words, not a full session — success in 3 minutes rebuilds the habit faster than a lecture.",
"Attach practice to an anchor that already happens daily: right after breakfast, in the car, before dessert. Habits stick to habits.",
"Let them teach YOU: ask your child to be the judge and read words for you to spell (make a few mistakes!). Being the expert re-hooks kids fast.",
"Restart in the Arcade, not the drill: one round of Buzz of the Day feels like play but quietly rebuilds the routine.",
"Put the streak calendar where they can see it — a visible chain kids can't bear to break beats any reminder from a parent.",
"Try a 'comeback challenge': three days in a row of any practice at all earns something small they pick. Momentum first, volume later.",
"Switch the list before pushing harder — boredom masquerades as laziness. A fresh Theme Journey in a world they love often restarts the engine.",
"Ask what felt heavy: too many words per session, words too hard, or sessions too long? Cut that one thing in half for a week.",
"Move practice to their best hour. A tired speller at 8pm learns half of what the same child learns at 8am on the weekend.",
"Do a 'win replay': open the heatmap and look at everything already mastered before starting. Starting from strength changes the whole session.",
"Make it social: invite a sibling, cousin or friend for one Beat-the-Buzzer face-off. Rivalry (the friendly kind) is rocket fuel.",
"If the app's daily goal feels far away, lower it. A goal met daily beats an ambitious goal met never — you can raise it again in two weeks.",
"Trade seats: you spell, they score. Ten minutes of judging you re-engages most kids without them noticing they're studying.",
"Skip the guilt talk entirely. 'We're starting fresh today' outperforms 'you haven't practised in a week' every single time."],
consistency:[
"Two 10-minute sessions beat one 40-minute session — spacing is the single most proven trick in all of memory science.",
"Same time, same place, every day: rituals remove the daily negotiation, and removing negotiation removes most of the friction.",
"Never miss twice: one skipped day is rest, two is a new habit. Guard the day AFTER a miss most fiercely.",
"Track effort, not results, on the fridge: 'practised today ✓' — mastery follows attendance.",
"Set the daily goal so low it's almost silly (5 words). Consistency at 5 builds the muscle that later carries 50.",
"Weekends are where streaks die — plan the weekend session's exact time on Friday night.",
"Use the streak rewards as family events: 7-day streak = pancake breakfast. Shared stakes keep everyone invested.",
"Let your child pick WHICH list each day, never WHETHER to practise. Autonomy inside a boundary is the sweet spot.",
"If evenings keep failing, move to mornings for one week as an experiment — frame it as science, not punishment.",
"A 'minimum day' rule saves streaks: on crazy days, one Buzz of the Day round counts. Something always beats nothing."],
difficult:[
"For a stubborn word, use the routine out loud together: say it, spell it in the air with big arm letters, say it again. Motion glues memory.",
"Break the word into its story: bouquet is French, so the /kay/ ending is -quet. A word with a story is a word remembered.",
"Have them write the hard word three ways: pencil, finger on the table, and eyes closed. Three channels, one memory.",
"Use the 'hot spot' trick: most misspellings are ONE letter. Find the exact letter they miss, circle it in red, and make it huge: defINitely.",
"Turn the miss into a mnemonic they invent (not you) — a kid's own silly hook ('the ISland IS land') outlasts any adult explanation.",
"Sleep on it: review a hard word right before bed, once. The sleeping brain files it better than five daytime repetitions.",
"Interleave: mix 3 hard words among 7 easy ones. All-hard sessions crush morale; the easy words carry the hard ones along.",
"Ask the app to say the word, then have your child say it back in a whisper, a shout, and a robot voice before spelling. Silly but it works.",
"For words that keep coming back wrong, check the FIRST attempt was corrected immediately — a wrong spelling rehearsed twice becomes twice as sticky.",
"Compare the miss with the fix side by side on paper: seperate / separate. The eye learns differences better than repetitions.",
"Trace the syllables on their palm as they spell each chunk: cal-en-dar. Touch anchors sequence.",
"Give hard words a 'parking lot': a card on the wall with this week's 5 nemesis words. Cross one off only after 3 clean spellings on 3 days.",
"Let them 'win an argument' with the word: why is it spelled that way? Look up the origin together in the app — understanding beats memorizing.",
"If a word simply won't stick, retire it for two weeks. Distance resets frustration, and it usually lands easily on return."],
memory:[
"Spaced beats crammed: the app already re-serves words at intervals — trust it, and resist re-drilling what was just mastered.",
"Retrieval beats review: asking 'spell harbor' works 3× better than showing the word again. Always test, don't re-show.",
"Chunk long words into 3-letter beats and spell in rhythm — the brain stores rhythms far better than letter strings.",
"Attach images to letters that lie: the silent b in lamb? Picture a lamb with a big B balloon tied to its tail.",
"Have them spell yesterday's words BEFORE learning today's — a 2-minute warm-up of old wins doubles retention.",
"Mix spelling directions: aloud, on paper, typed, backwards for fun. Varied practice builds flexible recall.",
"The 'explain it to a toddler' test: if your child can explain WHY a word is spelled its way, that word is permanent.",
"Songs work: spell tricky words to the tune of Happy Birthday. Melody is the oldest memory technology we have.",
"Keep sessions under 20 minutes — attention drops off a cliff after that, and words studied on the cliff don't stick.",
"Celebrate the third clean recall, not the first: one correct spelling is luck, three across days is mastery.",
"Handwriting engages deeper memory than typing for new words; type for speed drills, write for first learning.",
"Before revealing a correction, let them find the error themselves: 'one letter is off — can you spot it?' Error-hunting is elite practice.",
"Group words by pattern, not alphabet: five -tion words together teach a rule; five random words teach five facts.",
"End every session on a word they get RIGHT. Last impressions set tomorrow's appetite."],
accuracy:[
"Slow the tempo: most accuracy dips are speed problems. Ask for a 2-second pause between hearing and spelling.",
"Reinstate the routine: say the word back before spelling — skipped say-backs are the #1 source of wrong-word errors.",
"Watch for guess-sprints: three fast wrong answers in a row means fatigue or frustration. Two-minute break, then resume.",
"Check the audio: if accuracy fell suddenly, make sure the volume is up and the room is quiet — mishearing looks identical to misspelling.",
"Review misses the same day they happen — a miss corrected within hours is 4× less likely to repeat.",
"Look for a pattern in the misses in the Parent log: all schwa endings? All doubles? One pattern fixed can lift accuracy 10%.",
"Praise the process not the score: 'you used the syllable trick!' builds the behavior that raises the score next week.",
"If accuracy is high but slow, leave it alone — speed follows accuracy naturally; forcing speed reverses both.",
"Below 60% on a list means the list is too hard right now. Drop a level, rebuild confidence, come back in two weeks.",
"Keep a 'caught it!' count: every time they catch their own error before submitting counts double. Self-correction is the real skill."],
oral:[
"Practise standing up, saying letters aloud — spelling in your head and spelling at a mic are different sports.",
"Teach the mic ritual: repeat the word, ask one question, pause two seconds, then spell steadily. Rituals absorb nerves.",
"Record them spelling five words on your phone and play it back — kids self-correct pace and clarity instantly when they hear themselves.",
"Play 'judge and speller' at dinner: anyone can be judge, house rule is the routine must be followed. Normalize the format.",
"Train the recovery: practise what to do when they realize mid-word something's wrong — stop, breathe, ask to start the word again (allowed once!).",
"Speed is the enemy on stage: a champion's spell is SLOWER than practice pace. Drill 'one letter per heartbeat'.",
"Alternate silent-typing days and aloud days — the oral rounds in the app mirror real elimination formats.",
"Have them spell with hands behind their back — many kids 'air-write' and lose their place when nervous; voice-only practice fixes it.",
"Do one 'distraction round' a week: TV on, sibling nearby. Stage conditions are never library conditions.",
"Teach the question menu until it's automatic: definition, origin, part of speech, sentence, alternate pronunciations. Questions buy thinking time."],
written:[
"In written rounds, teach the scan-back: after typing each word, one 1-second look before Enter catches a third of all slips.",
"Simulate real conditions once a week: full written round, timer on, no do-overs. Then review together calmly.",
"Watch their FIRST instinct — in written tests the first spelling is usually right; endless erasing often makes it worse. Track which is true for your child.",
"Practise neat, fast handwriting for paper bees separately — points lost to illegible letters are the saddest points of all.",
"Number sense matters: in a 25-word written round, teach them to bank the 20 easy ones fast, then spend remaining time on the 5 hard ones.",
"Review written rounds by error type: heard wrong / knew it but slipped / never knew it. Each type gets a different fix.",
"Train silent pronunciation: mouthing the word before writing engages the ear pathway even in a silent room.",
"After each written round, have your child pick ONE word they want to never miss again — self-chosen targets get fixed twice as fast."],
beeday:[
"In the final two weeks, shift from learning new words to defending known ones — reviews, not frontiers.",
"Simulate the schedule: practise at the same hour the bee happens, at least twice in the last week.",
"Plan the morning: usual breakfast (nothing new!), arrive early, one short warm-up list — then STOP studying an hour before.",
"Pack a bee-day kit together the night before: water, a snack, a sweater (venues are cold), and one lucky object. Preparation calms.",
"Agree on the after-plan regardless of result: 'pizza either way.' Removing outcome-stakes paradoxically improves outcomes.",
"Front-load sleep: the two nights BEFORE the night before matter most. A sleep-deprived brain misplaces schwas.",
"Teach the shrug ritual for a missed word: shrug, breathe, 'next one's mine.' Recovery speed decides multi-round bees.",
"Watch other spellers as teammates, not rivals: kids who clap for others stay looser and spell better.",
"Do a venue walkthrough if allowed — a stage seen once before is half as scary.",
"Keep YOUR face calm in the audience: kids read parents' faces mid-word. Practise your poker smile.",
"No new mnemonics on bee day — last-minute tricks overwrite stable memories. Bee day is for trust, not training.",
"Remind them the mic is a friend: it means the judges WANT to hear their brilliant spelling. Framing beats fear."],
nerves:[
"Box breathing before stage time: in 4, hold 4, out 4, hold 4 — two rounds, invisible to everyone, lowers heart rate measurably.",
"Rename the feeling: 'excited' and 'nervous' are the same body signals — kids who say 'I'm excited' perform better. Words steer chemistry.",
"Rehearse the worst case out loud once: 'if I miss, I sit down, and we get ice cream.' A named fear is a shrunken fear.",
"Give their hands a job: thumb pressed to each fingertip in sequence while thinking. Busy hands quiet minds.",
"Confidence is a deposit account: every clean practice round this month is a deposit. Remind them how full the account is.",
"Practise the pause: standing silent for 5 seconds at a pretend mic, comfortably. Silence feels 5× longer on stage — pre-stretch it.",
"Never make the bee the family's only topic in the final week — brains under a spotlight seize up. Keep normal life loud.",
"A power pose backstage (hands on hips, 30 seconds, superhero face) is silly, private, and genuinely works for kids."],
motivation:[
"Motivation follows mastery, not the reverse: engineer one easy win at the start of every session.",
"Use identity praise once a week, max: 'you're becoming a real word detective' lands deeper than daily 'good job'.",
"Let them spend their coins! The shop's themes and boosts exist so effort turns into visible, chosen rewards.",
"Post the 'wall of beaten words' — every retired nemesis word goes up. Kids fight harder for visible territory.",
"Ask 'which word surprised you today?' instead of 'how did practice go?' — curiosity questions get curiosity answers.",
"Tie big milestones to experiences, not things: Level 10 = choosing Saturday's family outing. Experiences don't wear off by Tuesday.",
"When they beat a personal best, have THEM call a grandparent to report it. Telling the story cements the pride.",
"Watch a real Scripps finals clip together once — seeing kids their age at the mic turns abstract goals into 'that could be me'.",
"Rotate the fun: one Arcade-only day per week keeps the app feeling like a game, not a chore.",
"If motivation dips, check difficulty first: too easy bores, too hard scares. The sweet spot is ~80% success.",
"Never compare siblings' levels out loud. Compare each child only to last month's version of themselves.",
"Let them set next week's goal themselves — kids over-commit slightly and then defend their own promises fiercely."],
parenting:[
"Be the studio audience, not the coach, during practice: react, laugh, gasp — correction is the app's job, delight is yours.",
"Keep a 'parent patience rule': one hint per word, max. Rescuing too early teaches waiting-to-be-rescued.",
"Practice WITH them sometimes: struggle at a word yourself. Watching a parent work through difficulty is the best masterclass.",
"Check the Parent dashboard weekly, not daily — daily numbers wobble, weekly trends tell the truth.",
"Guard the identity: 'a speller who had a bad day', never 'maybe spelling isn't your thing'. Labels last longer than results.",
"Print the weekly report and let your child present it to the family like a CEO. Ownership of data builds ownership of effort.",
"If a session turns into tears, end it warmly and immediately. One bad emotional association costs ten good sessions.",
"Ask your child to explain one spelling rule to you per week — teaching is the highest form of knowing.",
"Keep bee talk to 15% of your conversations. Kids who are 'more than their bee' spell more freely at the bee.",
"When they lose a word they 'knew', normalize it: even champions miss known words. The log, not the moment, tells the story.",
"Your calm is contagious equipment: pack it every session.",
"Schedule practice like piano lessons — a fixed family fixture, not a daily negotiation that drains everyone."],
young:[
"For younger spellers, keep sessions to 10 minutes and end mid-fun — leaving them slightly hungry brings them back tomorrow.",
"Use body spelling: jump for tall letters (t, l, k), crouch for tails (g, y, p). Younger kids encode with their whole bodies.",
"Magnetic letters on the fridge for the week's 5 words — incidental glances count as reviews.",
"Sound-first, letter-second: have little ones stretch the word like a rubber band before any letters are named.",
"Let them decorate mastered words with stickers in a notebook — a physical trophy book beats digital badges at this age.",
"Read aloud daily, anything at all — vocabulary breadth is the raw material every speller is built from.",
"Rhyme games in the car ('what rhymes with light?') secretly drill the -ight family. Stealth spelling is real spelling.",
"Keep corrections featherlight: 'ooh, SO close — one letter is playing hide and seek.' Drama-free errors keep hands raised."],
plateau:[
"Plateaus are consolidation, not failure — the brain is filing. Hold steady for two weeks before changing anything.",
"Break a plateau by changing the FORMAT, not the effort: switch from typing to oral rounds, or drills to Boss Battle.",
"Recheck the level: plateaus often mean the current level was passed on luck. One level down for one week rebuilds the floor.",
"Introduce a 'stretch word' ritual: one word well above level, daily, just for adventure. Stretch resets the challenge appetite.",
"Audit sleep and schedule before auditing talent — most plateaus in kids track to a new activity eating their best hours.",
"Rotate lists: two weeks in a Theme Journey they love often unsticks a stuck main-list ladder.",
"Set a micro-goal unrelated to levels: '95% on doubles this week'. Narrow wins restart wide progress.",
"Show them their own graph from a month ago — plateaus feel eternal to kids; evidence of past climbing reframes today."],
review:[
"The missed-words list is gold: 10 minutes there is worth 30 minutes of new words.",
"Schedule a weekly 'revenge round' — only past misses. Kids love beating words that once beat them.",
"After a word is re-mastered, ask what trick finally worked — naming the fix turns one win into a strategy.",
"Don't let the review pile exceed ~20 words; big piles intimidate. Chip daily, keep it short.",
"Interleave one old miss into every new session as a 'surprise guest'. Randomized review is the strongest kind.",
"Review right before bed twice a week — sleep consolidation is free tutoring.",
"Watch for words missed 3+ times in the Parent log: those need a full story treatment (origin, hook, drawing), not another drill.",
"Celebrate an emptied review list like a level-up. Zero-debt weeks deserve noise."],
coverage:[
"Breadth first, four weeks out or more: new words daily, light review. The app's plan follows this — trust the phase.",
"Use 'New set' when a level feels stale — fresh words within the same level keep coverage moving without difficulty jumps.",
"A little every list beats a lot on one list: 5 minutes on the theme list after the main session widens the net cheaply.",
"Check the Library meter monthly, not weekly — coverage is a marathon metric.",
"When coverage is low but accuracy is high, raise the daily goal by 2 — your child has headroom to spare."],
origin:[
"Teach the origin shortcuts as a family code: French = silent endings (ballet), Greek = ph and ch-as-k (chorus), Spanish = every vowel speaks (tornado).",
"When a word is missed, look up its origin together in the app — the story of WHY it's spelled that way is the strongest mnemonic there is.",
"Drill one origin list per fortnight (the app has Latin, Greek, French and more) — origins cluster spelling patterns like nothing else.",
"Play 'guess the language' with dinner-table words: spaghetti? kindergarten? ballet? The Origin Detective game does this with real bee words.",
"German loanwords keep their crunch (kindergarten, pretzel); Japanese ones end open (karate, tsunami). Ten minutes of examples builds lifelong radar.",
"The schwa in a mystery word often resolves through origin: Latin -or (doctor), French -er/-re (theatre). Ask 'where's it from?' before guessing letters.",
"Sanskrit and Hindi loanwords (guru, bungalow, juggernaut) delight kids with their stories — use them as the fun course between heavy drills.",
"Make origin questions reflexive at practice: every 5th word, ask 'what language do you THINK it is?' before revealing. Prediction locks learning."],
/* Added Aug 2026. The library above was written when the app was Practice plus a word
   list. It has since grown the Word Atlas, a vocabulary ladder with its own progression,
   the Arcade, Theme Journeys, the Advanced Pack and a placement-driven word difficulty —
   and a parent was never told a word about any of them, because parentSignals() could not
   see them. These categories are matched by the new if-this-then rules in parentTips(). */
atlas:[
"The Word Atlas is the spine of the course, not a side quest: each stop teaches a concept, meets its words, then gates on a real quiz. Ten minutes there is worth more than half an hour of loose practice.",
"If the Atlas has stalled, open the stop together once. Almost every child who stops does it at the quiz gate, and almost every one of those needs company for exactly one attempt.",
"A stop asks for 80% to pass, and that is deliberate — it is the number that means the concept stuck rather than the words did. A near miss is information, not a setback.",
"Atlas progress moves in laps: finishing every stop unlocks the same road at a harder band. A child who says they have 'done it' has usually done lap one of three.",
],
vocab:[
"Spelling and vocabulary are separate ladders in this app, on purpose — a child can spell far past what they can define, and the bee asks for both. If the spelling level is climbing and vocabulary is untouched, that gap will show up on a meaning question.",
"The vocabulary check is four-option multiple choice and it never touches spelling progress. It is safe to attempt badly, which makes it the cheapest way to find out what a word actually means to them.",
"Any word list can be studied for meaning, not just the vocabulary decks. If they are drilling a list for spelling, run the same list as vocabulary a week later — same words, different muscle.",
],
themes:[
"Interest is memory glue. A Theme Journey groups words by what they are ABOUT — space, food, myth, medicine — and a child remembers a word met inside something they care about far longer than one met in an alphabetical list.",
"Themes also teach by ORIGIN, not only by meaning. The origin families are the fastest route to the language-of-origin habit that decides hard spellings at the bee.",
"Let them pick the theme. A journey chosen by a child is practised; a journey assigned by an adult is completed.",
],
arcade:[
"The Arcade is practice wearing a costume — every game makes the child produce a spelling, not just recognise one. For a child who resists drills, this is the drill.",
"After a game the result card lists every word it asked for, with the correct spelling and a one-tap way onto the revision pile. That list is the useful part; the score is the bait.",
"Difficulty is set per game, not once for the whole room. If a game feels punishing, drop that one game a level rather than making everything easier.",
],
advanced:[
"Above about level six the words stop being predictable from sound, and origin, roots and routine become the whole game. That is the point where the Advanced Pack's expert chapters start to matter more than more practice.",
"If you are weighing the Advanced Pack, look at the misses rather than the level: when a child is losing words to Greek and Latin patterns rather than to carelessness, the expert chapters are what is missing.",
],
placement:[
"The app is still working out the right word difficulty. Let them practise normally for a few sessions — every graded word is evidence, and a level guessed from a handful of words is worse than one earned from thirty.",
"Do not hand-set the level to flatter or to stretch. Words too easy teach nothing and words too hard teach avoidance; the ramp finds the edge faster than an adult can.",
],
};