/* Bizzing Bee — supplemental words for the core engine.
   Rare/foreign-origin "bee" words (Visagiste & friends) plus difficult words drawn
   from the Quotes library, so every highlighted quote word is also practisable.
   Appended to SB_DATA.nsf. Definitions/etymology hand-checked; sentences masked-safe. */
(function(){
  var extra=[
  // ---- rare & foreign-origin words (Visagiste-caliber) ----
  {w:"visagiste",d:"a professional artist who applies and designs makeup, especially for the face",s:"Before the fashion show, the model sat patiently while the ▁▁▁ blended shades across her cheekbones.",p:"vee-zah-ZHEEST",o:"French",y:4,bp:98,ps:"noun",r:"French 'visage' (face) + -iste (one who does)",h:"Think VISAGE (face) — a visagiste works on the face.",nt:"Advanced | French origin",t:["french","art"]},
  {w:"apricity",d:"the warmth of the sun felt on a cold winter's day",s:"Wrapped in a scarf on the bench, she closed her eyes and soaked up the gentle ▁▁▁.",p:"uh-PRIS-ih-tee",o:"Latin",y:4,bp:97,ps:"noun",r:"Latin 'apricus' (sunny, exposed to the sun)",h:"Rare word for winter sunshine — root 'apric' means sunny.",nt:"Advanced | Latin origin",t:["latin","weather"]},
  {w:"bruxism",d:"the habit of grinding or clenching the teeth, often during sleep",s:"The dentist noticed worn enamel and gently asked whether stress was causing some nighttime ▁▁▁.",p:"BRUK-siz-um",o:"Greek",y:4,bp:96,ps:"noun",r:"Greek 'brykein' (to gnash the teeth) + -ism",h:"'brux' = to gnash — a teeth-grinding habit.",nt:"Advanced | Greek origin",t:["greek","medical"]},
  {w:"collywobbles",d:"a feeling of nervousness, or a rumbling, uneasy stomach",s:"Waiting backstage for his turn to spell, Diego felt a fluttering case of the ▁▁▁.",p:"KOL-ee-wob-ulz",o:"English",y:3,bp:88,ps:"noun",r:"A fanciful English word, perhaps from 'colic' + 'wobble'",h:"A playful word for a nervous, wobbly tummy.",nt:"Advanced | fanciful English",t:["english","feelings"]},
  {w:"eldritch",d:"strange and frightening in an eerie, otherworldly way",s:"An ▁▁▁ green glow flickered deep inside the abandoned lighthouse.",p:"EL-drich",o:"Scots",y:4,bp:95,ps:"adjective",r:"Probably Old English 'el-' (foreign, strange) + 'rice' (realm)",h:"Means eerie or weird — often used in spooky stories.",nt:"Advanced | Scots/Old English",t:["english","spooky"]},
  {w:"fahrvergnugen",d:"the pleasure or enjoyment that comes from driving",s:"Cruising down the open coastal road, Dad grinned and called it pure ▁▁▁.",p:"fahr-fer-GNOO-gen",o:"German",y:4,bp:99,ps:"noun",r:"German 'fahren' (to drive) + 'Vergnügen' (enjoyment)",h:"German compound — 'driving' + 'enjoyment'.",nt:"Advanced | German origin",t:["german"]},
  {w:"fernweh",d:"a strong longing for far-off places; the opposite of homesickness",s:"Reading about mountains and deserts filled her with a restless ▁▁▁.",p:"FERN-vay",o:"German",y:4,bp:96,ps:"noun",r:"German 'fern' (far) + 'Weh' (ache, pain)",h:"'far' + 'ache' — an ache to travel far away.",nt:"Advanced | German origin",t:["german","feelings"]},
  {w:"flibbertigibbet",d:"a silly, restless, or overly talkative person",s:"Too excited to sit still, the little ▁▁▁ chattered through the whole assembly.",p:"FLIB-er-tee-jib-it",o:"English",y:4,bp:94,ps:"noun",r:"An imitative Middle English word suggesting idle chatter",h:"A long, fun word for a flighty chatterbox.",nt:"Advanced | English",t:["english","people"]},
  {w:"gesundheit",d:"a word said to someone who has just sneezed, wishing them good health",s:"Achoo! Grandpa smiled and offered a cheerful ▁▁▁.",p:"guh-ZUUNT-hyt",o:"German",y:3,bp:90,ps:"interjection",r:"German 'gesund' (healthy) + '-heit' (state of)",h:"German for 'health' — said after a sneeze.",nt:"Advanced | German origin",t:["german"]},
  {w:"gouache",d:"a way of painting with thick, opaque watercolors, or the paints themselves",s:"She layered rich blues in ▁▁▁ until the night sky looked almost solid.",p:"gwahsh",o:"French",y:4,bp:93,ps:"noun",r:"French, from Italian 'guazzo' (watercolor, puddle)",h:"An art word — opaque watercolor paint.",nt:"Advanced | French origin",t:["french","art"]},
  {w:"hiraeth",d:"a deep, wistful longing for a home or time you can never truly return to",s:"Old photographs of the village stirred a quiet ▁▁▁ in her heart.",p:"HEER-ith",o:"Welsh",y:4,bp:97,ps:"noun",r:"Welsh, with no exact English translation",h:"A Welsh word for homesick longing.",nt:"Advanced | Welsh origin",t:["welsh","feelings"]},
  {w:"hullabaloo",d:"a great noise, fuss, or commotion",s:"A whole ▁▁▁ broke out in the stands when the winning goal went in.",p:"HUL-uh-buh-loo",o:"English",y:3,bp:85,ps:"noun",r:"A reduplicated English word imitating uproar",h:"A noisy fuss or uproar.",nt:"Advanced | English",t:["english"]},
  {w:"kerfuffle",d:"a commotion or fuss, especially one caused by a disagreement",s:"There was a small ▁▁▁ at the door over who had arrived first.",p:"ker-FUF-ul",o:"Scots",y:3,bp:87,ps:"noun",r:"Scots 'curfuffle', from 'car-' (twist) + 'fuffle' (to disorder)",h:"A minor commotion or fuss.",nt:"Advanced | Scots origin",t:["scots"]},
  {w:"kummerspeck",d:"extra weight gained from emotional overeating (literally 'grief bacon')",s:"After a gloomy, snack-filled week, he joked about a little ▁▁▁.",p:"KUUM-er-shpek",o:"German",y:4,bp:98,ps:"noun",r:"German 'Kummer' (grief) + 'Speck' (bacon, fat)",h:"German 'grief' + 'bacon' — comfort-eating weight.",nt:"Advanced | German origin",t:["german"]},
  {w:"limpid",d:"perfectly clear and transparent",s:"They could see straight to the pebbles through the ▁▁▁ mountain stream.",p:"LIM-pid",o:"Latin",y:3,bp:89,ps:"adjective",r:"Latin 'limpidus' (clear)",h:"Means crystal clear — like limpid water.",nt:"Advanced | Latin origin",t:["latin","nature"]},
  {w:"lollapalooza",d:"an especially remarkable or wonderful person or thing",s:"That last magic trick was an absolute ▁▁▁ — the crowd gasped.",p:"lol-uh-puh-LOO-zuh",o:"English",y:4,bp:92,ps:"noun",r:"An early-1900s American slang coinage",h:"Slang for something outstanding.",nt:"Advanced | American English",t:["english"]},
  {w:"niche",d:"a comfortable or perfectly suited position; also a small recess in a wall",s:"After trying many hobbies, she finally found her ▁▁▁ in astronomy club.",p:"neesh",o:"French",y:3,bp:84,ps:"noun",r:"French 'nicher' (to nest), from Latin 'nidus' (nest)",h:"A cozy spot that fits you just right.",nt:"Advanced | French origin",t:["french"]},
  {w:"numinous",d:"filled with a strong sense of something holy, mysterious, or awe-inspiring",s:"Standing beneath the vast cathedral dome, they felt a ▁▁▁ hush.",p:"NOO-mih-nus",o:"Latin",y:4,bp:95,ps:"adjective",r:"Latin 'numen' (divine power, a nod of the god's head)",h:"Root 'numen' = divine presence — awe-filled.",nt:"Advanced | Latin origin",t:["latin"]},
  {w:"petrichor",d:"the pleasant earthy smell that rises after rain falls on dry ground",s:"The first drops hit the pavement and released that unmistakable ▁▁▁.",p:"PET-rih-kor",o:"Greek",y:4,bp:96,ps:"noun",r:"Greek 'petra' (stone) + 'ichor' (fluid of the gods)",h:"'petr' = stone — the smell of rain on stone.",nt:"Advanced | Greek origin",t:["greek","nature"]},
  {w:"protege",d:"a young person who is taught and helped by an older, more experienced one",s:"The champion coach beamed as her ▁▁▁ lifted the regional trophy.",p:"PROH-tuh-zhay",o:"French",y:3,bp:86,ps:"noun",r:"French 'protéger' (to protect), from Latin 'protegere'",h:"Root 'proteg' = protect — a protected learner.",nt:"Advanced | French origin",t:["french"]},
  {w:"quixotic",d:"wildly idealistic and hopeful, but not very practical",s:"His ▁▁▁ plan to plant a million trees in a week made everyone smile.",p:"kwik-SOT-ik",o:"Spanish",y:4,bp:94,ps:"adjective",r:"From Don Quixote, the dreamy hero of Cervantes' novel",h:"From Don Quixote — grandly impractical.",nt:"Advanced | Spanish/literary",t:["spanish","literature"]},
  {w:"risque",d:"slightly daring or cheeky; a little bit improper",s:"The comedian's gently ▁▁▁ joke made the grown-ups chuckle.",p:"ris-KAY",o:"French",y:3,bp:88,ps:"adjective",r:"French 'risquer' (to risk)",h:"Root 'risqu' = risk — a touch daring.",nt:"Advanced | French origin",t:["french"]},
  {w:"saudade",d:"a deep, bittersweet longing for someone or something loved and now far away",s:"The old sailor's song was full of ▁▁▁ for the harbor he had left behind.",p:"sow-DAH-duh",o:"Portuguese",y:4,bp:97,ps:"noun",r:"Portuguese, with no exact English equivalent",h:"A Portuguese word for tender longing.",nt:"Advanced | Portuguese origin",t:["portuguese","feelings"]},
  {w:"secretaire",d:"a writing desk fitted with small drawers and compartments",s:"Grandmother kept her letters locked in the little ▁▁▁ by the window.",p:"sek-ruh-TAIR",o:"French",y:4,bp:93,ps:"noun",r:"French 'secrétaire' (secretary, writing desk)",h:"A fancy French writing desk.",nt:"Advanced | French origin",t:["french"]},
  {w:"smorgasbord",d:"a wide range of tasty dishes served as a buffet; a varied assortment",s:"The festival offered a ▁▁▁ of snacks from a dozen different countries.",p:"SMOR-gus-bord",o:"Swedish",y:3,bp:87,ps:"noun",r:"Swedish 'smörgås' (open sandwich) + 'bord' (table)",h:"Swedish 'sandwich-table' — a big buffet.",nt:"Advanced | Swedish origin",t:["swedish","food"]},
  {w:"sprachgefuhl",d:"an intuitive feeling for what sounds right and natural in a language",s:"After years of reading, she developed a keen ▁▁▁ for graceful sentences.",p:"SHPRAHK-guh-fuul",o:"German",y:4,bp:99,ps:"noun",r:"German 'Sprache' (language) + 'Gefühl' (feeling)",h:"German 'language' + 'feeling'.",nt:"Advanced | German origin",t:["german","language"]},
  {w:"touche",d:"a word used to admit that someone has made a clever or fair point",s:"When she out-argued him with a grin, he simply raised his hands and said ▁▁▁.",p:"too-SHAY",o:"French",y:3,bp:85,ps:"interjection",r:"French 'touché' (touched), from fencing when a hit lands",h:"From fencing — 'you got me!'",nt:"Advanced | French origin",t:["french"]},
  {w:"velleity",d:"a wish or desire too weak to lead you to actually do anything about it",s:"His plan to learn the violin never got past a faint ▁▁▁.",p:"vuh-LEE-ih-tee",o:"Latin",y:4,bp:96,ps:"noun",r:"Latin 'velle' (to wish)",h:"Root 'velle' = to wish — a wish without action.",nt:"Advanced | Latin origin",t:["latin"]},
  {w:"voila",d:"there it is; a word used to draw attention to something just revealed",s:"She lifted the cloth and — ▁▁▁ — a perfect birthday cake appeared.",p:"vwah-LAH",o:"French",y:2,bp:78,ps:"interjection",r:"French 'voir' (to see) + 'là' (there)",h:"French 'see there!' — ta-da!",nt:"French origin",t:["french"]},
  {w:"widdershins",d:"in a direction opposite to the usual; counterclockwise",s:"In the old tale, walking ▁▁▁ around the tower was said to bring bad luck.",p:"WID-er-shinz",o:"Low German",y:4,bp:95,ps:"adverb",r:"Middle Low German 'weddersins' (against the way)",h:"Old word for counterclockwise.",nt:"Advanced | Low German origin",t:["german","folklore"]},
  {w:"aplomb",d:"calm self-confidence and poise, especially in a tricky situation",s:"She answered the surprise question with remarkable ▁▁▁.",p:"uh-PLOM",o:"French",y:3,bp:90,ps:"noun",r:"French 'à plomb' (straight down, like a plumb line)",h:"Steady as a plumb line — cool poise.",nt:"Advanced | French origin",t:["french"]},
  {w:"consummation",d:"the point at which something is finally completed or made perfect",s:"Winning nationals was the ▁▁▁ of years of early-morning practice.",p:"kon-suh-MAY-shun",o:"Latin",y:4,bp:92,ps:"noun",r:"Latin 'consummare' (to bring to the highest point)",h:"Root 'summ' = highest — a completing.",nt:"Advanced | Latin | seen in Hamlet",t:["latin","literature"]},
  {w:"perchance",d:"an old-fashioned word meaning perhaps or possibly",s:"▁▁▁ the rain will hold off until the picnic is over.",p:"per-CHANS",o:"French",y:3,bp:83,ps:"adverb",r:"Old French 'par cheance' (by chance)",h:"Old word for 'maybe' — famous in Shakespeare.",nt:"Advanced | archaic | seen in Hamlet",t:["french","literature"]},
  // ---- difficult words drawn from the Quotes library (lemmas) ----
  {w:"noble",d:"having or showing fine personal qualities such as honesty and courage",s:"It was a ▁▁▁ choice to give up her prize so a friend could compete.",p:"NOH-bul",o:"Latin",y:2,bp:70,ps:"adjective",r:"Latin 'nobilis' (well known, high-born)",h:"Comparative 'nobler' — finer, more honourable.",nt:"seen in Hamlet",t:["latin","character"]},
  {w:"sling",d:"a loop of material used to hurl a stone, or to support an injured arm",s:"David loaded a smooth pebble into his ▁▁▁ and took careful aim.",p:"sling",o:"Germanic",y:2,bp:60,ps:"noun",r:"Middle English, of Germanic origin",h:"Plural 'slings' — as in 'slings and arrows'.",nt:"seen in Hamlet",t:["english"]},
  {w:"passion",d:"a very strong feeling or emotion, such as great love or excitement",s:"Her ▁▁▁ for the stars turned into a lifelong love of astronomy.",p:"PASH-un",o:"Latin",y:2,bp:66,ps:"noun",r:"Latin 'passio' (suffering, strong feeling)",h:"Strong emotion — plural 'passions'.",nt:"seen in The Merchant of Venice",t:["latin","feelings"]},
  {w:"vale",d:"a valley, especially a broad one (a poetic word)",s:"Sunlight spilled across the green ▁▁▁ between the two hills.",p:"vayl",o:"Latin",y:3,bp:80,ps:"noun",r:"Old French 'val', from Latin 'vallis' (valley)",h:"Poetic word for valley — plural 'vales'.",nt:"seen in Wordsworth",t:["latin","nature"]},
  {w:"perch",d:"to sit or rest on something, the way a bird settles on a branch",s:"A tiny sparrow came to ▁▁▁ on the very top of the fence.",p:"purch",o:"Latin",y:2,bp:58,ps:"verb",r:"Old French 'perche', from Latin 'pertica' (pole)",h:"Birds perch; 'perches' in the poem.",nt:"seen in Dickinson",t:["latin","nature"]},
  {w:"diverge",d:"to separate and move off in different directions",s:"The two trails ▁▁▁ at the old oak, one climbing and one dipping.",p:"dih-VURJ",o:"Latin",y:3,bp:79,ps:"verb",r:"Latin 'di-' (apart) + 'vergere' (to turn)",h:"Past tense 'diverged' — split apart.",nt:"seen in Robert Frost",t:["latin"]},
  {w:"prick",d:"to pierce or poke slightly with a sharp point",s:"Be careful not to ▁▁▁ your finger on the rose's thorn.",p:"prik",o:"English",y:1,bp:45,ps:"verb",r:"Old English 'prician' (to pierce)",h:"A tiny sharp poke.",nt:"seen in The Merchant of Venice",t:["english"]},
  {w:"err",d:"to make a mistake or do something wrong",s:"Even the best spellers sometimes ▁▁▁ on a tricky silent letter.",p:"ur",o:"Latin",y:2,bp:64,ps:"verb",r:"Latin 'errare' (to wander, to stray)",h:"To err is human — root 'err' = to wander.",nt:"seen in Alexander Pope",t:["latin"]},
  {w:"eternal",d:"lasting forever; without beginning or end",s:"The stars felt ▁▁▁, glittering above the campsite all night long.",p:"ih-TUR-nul",o:"Latin",y:2,bp:68,ps:"adjective",r:"Latin 'aeternus' (everlasting)",h:"Root 'etern' = age/forever.",nt:"seen in Alexander Pope",t:["latin"]},
  {w:"breast",d:"the front upper part of the chest",s:"The robin puffed out its bright red ▁▁▁ against the frost.",p:"brest",o:"English",y:2,bp:55,ps:"noun",r:"Old English 'breost'",h:"Tricky spelling — silent 'ea'.",nt:"seen in Alexander Pope",t:["english"]},
  {w:"content",d:"the things that are held or contained inside something",s:"She poured out the ▁▁▁ of the jar to count the marbles.",p:"KON-tent",o:"Latin",y:2,bp:62,ps:"noun",r:"Latin 'contentum' (that which is contained)",h:"What's inside — the substance.",nt:"seen in Martin Luther King Jr.",t:["latin"]},
  {w:"host",d:"a very large number of people or things; also a person who receives guests",s:"A whole ▁▁▁ of golden daffodils danced along the lake.",p:"hohst",o:"Latin",y:2,bp:57,ps:"noun",r:"Latin 'hostis' (stranger, army), later 'a multitude'",h:"Means a big crowd — as in a host of stars.",nt:"seen in Wordsworth",t:["latin"]},
  {w:"subject",d:"a topic being discussed; also, likely to be affected by something",s:"The tricky ▁▁▁ of silent letters came up again in class.",p:"SUB-jekt",o:"Latin",y:2,bp:63,ps:"noun",r:"Latin 'subjectus' (brought under)",h:"Root 'ject' = throw; sub-ject = thrown under.",nt:"seen in The Merchant of Venice",t:["latin"]},
  {w:"rub",d:"to move something back and forth against a surface; also, a small difficulty",s:"Give the lamp a gentle ▁▁▁ and see what happens.",p:"rub",o:"English",y:1,bp:40,ps:"verb",r:"Middle English, probably of Low German origin",h:"'There's the rub' — the catch or snag.",nt:"seen in Hamlet",t:["english"]},
  {w:"divine",d:"relating to or coming from God; or simply wonderful",s:"The choir's ▁▁▁ harmony seemed to float up to the ceiling.",p:"dih-VYN",o:"Latin",y:2,bp:69,ps:"adjective",r:"Latin 'divinus' (of a god)",h:"Root 'divin' = of the gods.",nt:"seen in Alexander Pope",t:["latin"]}
  ];
  try{
    if(!window.SB_DATA) window.SB_DATA={};
    if(!window.SB_DATA.nsf) window.SB_DATA.nsf=[];
    var have={}; for(var i=0;i<window.SB_DATA.nsf.length;i++){ var e=window.SB_DATA.nsf[i]; if(e&&e.w) have[String(e.w).toLowerCase()]=1; }
    for(var j=0;j<extra.length;j++){ var x=extra[j]; if(x&&x.w && !have[String(x.w).toLowerCase()]){ window.SB_DATA.nsf.push(x); have[String(x.w).toLowerCase()]=1; } }
  }catch(e){}
})();
